### ISSUE TITLE
[Bug] I can't click on balls anymore to report them.

### ISSUE THREAD

**Issue by NugaSausage** [tagpro-game/tagpro-issues#100]
I don't know if anyone else is having this problem, but now I can't report people by clicking on them (I have a touchscreen laptop, but neither touching the screen and their ball, nor using the mouse, works), and I have to open up the scoreboard to report. I have nothing else but the Mod Manager on right now.

Clicking on the balls is so convenient, and I would like some help.

**Comment by AMorporkian** [comment]
Please let us know your browser, screen resolution, and video settings so I can attempt to replicate.

**Comment by NugaSausage** [comment]
Okay for some reason this got resolved, though I'm not sure what I did. Closing issue.

**Comment by steppin** [comment]
yeah, i saw something similar in #81 that I haven't looked into yet
