### ISSUE TITLE
[Bug] About 5 times now, I won a game, with my stats on, and it didn't count for my stats. This hasn't happened after I lost. All the games lasted over 1 minute

### ISSUE THREAD

**Issue by goodluckhavefun123** [tagpro-game/tagpro-issues#108]

**Comment by NugaSausage** [comment]
Any userscripts or extensions on? Browser? 

Details can help to try to diagnose things :)

**Comment by goodluckhavefun123** [comment]
I have Tagpro Toolkit on, but it is not working. I am using Chrome: Version 39.0.2171.99 (64-bit)

**Comment by goodluckhavefun123** [comment]
THIS JUST HAPPENED AGAIN!!! in a 4 minute game

**Comment by Nick-Riggs** [comment]
It's possible for this to happen if the game feels you didn't contribute enough during your time in the game. 

The code exists to prevent people from running all day bots to collect rank points. Sometimes it raises false positives, but it shouldn't happen often.

**Comment by goodluckhavefun123** [comment]
Ok; thank you.

**Comment by goodluckhavefun123** [comment]
![screen shot 2015-01-20 at 7 26 30 pm](https://cloud.githubusercontent.com/assets/10569709/5829072/a91d4740-a0da-11e4-803d-dab781434aef.png)

Is three caps and switching teams not contributing enough?

**Comment by goodluckhavefun123** [comment]
My stats are on and I earned 0 rank points.

**Comment by NewCompte** [comment]
There seem to be a bug.

Also, Horseclock should have earned more than 0 points.

**Comment by goodluckhavefun123** [comment]
Yes; I hope this doesn't prevent me from earning the weekly.

**Comment by steppin** [comment]
has this ever happened to you where you have not switched teams?  If you are not sure it is ok, but if you are user, please let us know.  Thanks!

**Comment by goodluckhavefun123** [comment]
I am not sure. Also , All my rank points have been reset. I was in second place for the weekly. PLEASE FIX

**Comment by goodluckhavefun123** [comment]
I don't know if you guys need this, but my profile is here: http://tagpro-radius.koalabeast.com/profile/535c335d7347e8296ac1bfaa

Should I continue going for the weekly (will my old points be restored?)

**Comment by AMorporkian** [comment]
We have just pushed a fix and will restore your rank points.

**Comment by AMorporkian** [comment]
Very sorry for that; the bug is on my head.

**Comment by goodluckhavefun123** [comment]
Thank you; how long will this take?

**Comment by goodluckhavefun123** [comment]
Also, if I were to miss out on the weekly by few rank points would I still be able to get it (because of not earning them multiple time when I should have?)

**Comment by NewCompte** [comment]
The bug that we fixed is only about that last screenshot. When you switch teams, instead of getting 5 points, your rank points were wiped out.

**Comment by goodluckhavefun123** [comment]
When will my rank points reset? Also, if I were to miss out on the weekly by few rank points would I still be able to get it because of not earning them multiple time when I should have, and for the time it took on this thread?

**Comment by NewCompte** [comment]
We will probably give you back a lot of points for weekly that you are now missing. (We put out your rank points from a backup.)

5 users have had this issue, we are trying to figure out what would be fair for them.

**Comment by AMorporkian** [comment]
I have given you 60 rank points for each game you played but wasn't counted towards your rank points.  I believe this is a more than reasonable exchange rate, and puts you more than comfortably back in second. I'm really sorry once again :(

**Comment by goodluckhavefun123** [comment]
Thank you. Should I close this thread now?

**Comment by AMorporkian** [comment]
I'll go ahead and close it :). Thanks for your prompt bug reporting, this could have gotten a **lot** worse if it hadn't been noticed quickly. :+1:
