### ISSUE TITLE
TagPro Lobby

### ISSUE THREAD

**Issue by Freshrr** [tagpro-game/tagpro-issues#109]
Have you ever wanted to meet with pub players after game? Ever just wanted to chat and roll around in a room full of fellow ... Players? If so the TagPro lobby is the place for you. The TagPro lobby would be a room full of ... Players that will be able to chat, roll around, and (when added) add friends to their friends list. The lobby would be a place for all players to just chill and check their FPS and PING before playing on the particular server. Their would be one lobby per server. Each lobby might hold up to 250 people.

**Comment by Moosemaster21** [comment]
This one should definitely be a more important issue, especially if the Kongregate push is ever going to happen. There could be so much socializing! And you could explain strategy to newer players outside of a game setting, so your team wouldn't lose while you're teaching!

**Comment by jufda** [comment]
Interesting idea. It would also be a good place to find people who want to make private (or pub) game groups. Currently the only way (provided by the game/website) to do that is talk while playing or in the very short time frame before or after game. I can see the lobby as a thing that would make Tagpro more popular. Especially if an easy way to form groups and invite people to them is provided integrated to it. Friends system and PMs with this and it would be awesome.

**Comment by Nick-Riggs** [comment]
This won't be implemented any time soon, if at all. I'm leaving it marked as "pie in the sky".
