### ISSUE TITLE
[Bug?]

### ISSUE THREAD

**Issue by goodluckhavefun123** [tagpro-game/tagpro-issues#110]
Every time since you fixed the other bug someone I played with has finished the game with 0 rank points.
![screen shot 2015-01-20 at 8 57 07 pm](https://cloud.githubusercontent.com/assets/10569709/5829942/2bb371b4-a0e7-11e4-9856-2cf668ec3eb5.png)

**Comment by goodluckhavefun123** [comment]
Rank points are all weird. I was in this game for about 1 minute:
![screen shot 2015-01-20 at 9 02 53 pm](https://cloud.githubusercontent.com/assets/10569709/5830009/f67705e6-a0e7-11e4-90ef-ac9f715922c0.png)

**Comment by AMorporkian** [comment]
Yup, we just fixed that bug. It should be filtering out to all the servers shortly.

**Comment by goodluckhavefun123** [comment]
Thank you.
