### ISSUE TITLE
[suggestion] powerup counter stat

### ISSUE THREAD

**Issue by ballparts** [tagpro-game/tagpro-issues#113]
it would be a new stat counting the number of pups a player picked up separated by type. does not need to go on the scoreboard, it could just be made part of the tagpro.players object. this would be cool for league stats analysis.

thanks!

**Comment by Nick-Riggs** [comment]
Yes, we are already planning to do this. Probably in the next major release.

**Comment by ballparts** [comment]
awesome, thanks!
