### ISSUE TITLE
Actual Gates

### ISSUE THREAD

**Issue by Freshrr** [tagpro-game/tagpro-issues#120]
#ActualGates

----

*Gates Should be 2x1 At least for them to work properly, but could be 1x1 if that is the map editors preference.*

---

**Types of Gates:**

----

**Button Only** : This Gate would either have a preset state of Opened or Closed. It would be controlled by a button, and once you get on it, it changes to the opposite state.

**Open/Close**: This Gate would change depending on its current state to the opposite state. It will stay in that state, until the button is acted upon again, in which it would again change to its opposite.

**Flickering Gates**: These Gates would control them selves changing state every x amount of seconds.

**One Way Gates**: Gates that are always open but only allow one way of transport through it. (ex: It might allow just one way UP, DOWN, RIGHT, or LEFT.

-------

**Comment by RonSpawnson** [comment]
I think "Toggle gates" would be a good term to describe a portion of the request.

**Comment by TagPro-PreciousRoy** [comment]
When I saw this, I thought the suggestion was going to be gates that turned to walls rather than a surface that pops you.

PS Can I just say, Fresh your avatar is amazing. Well done.

**Comment by jufda** [comment]
Toggle gates would make the gates a bit too complicated, and confuse newbies even more.

Open/Closed Gate is interesting idea, and it's basically team neutral version of green gate that turns red/blue, or inactive gate that turns green when a player of either team rolls on it.

Flickering gates is another thing that would make the difference between good and bad (or old and new) players even bigger. We have enough timed things with bombs, boosts and power-ups.

One-way gates are the best idea in this IMO. They are easy to differentiate from normal gates (arrow-texture) and would be intuitive, make the map-making more interesting and open new possibilities to gameplay.

**Comment by Nick-Riggs** [comment]
We are considering implementing this with a switch tile to complement the button tile. When touched it would remained switched for X seconds before return to it's off position. 

In the case of gates, they would remain in their switched  positions for X seconds. In case of bombs, they would detonate after X seconds.
