### ISSUE TITLE
[Bug] I just played a match where I received little map data. I could not interact with game elements.

### ISSUE THREAD

**Issue by I-mess-up** [tagpro-game/tagpro-issues#122]
I received no data other than gate status, player spawns, boost and bomb status, powerup status, and player pops. I could not interact with game elements. I got a screen recording. The link is http://youtu.be/0uaE3ems_Yc.

Refreshing fixed my issue, but this was really weird.

Here are the scripts and extensions I am using:
TagPro Replays
Tampermonkey with:
- Gecko Tools
- Private group maker
- TagPro Chat macros userscript
- Honk
- Poker Chip Spin
- Catstats
- Spectator Center and Move
- TagPro tile pattern

**Comment by AMorporkian** [comment]
With all of those userscripts we can't possibly narrow down what might have caused it. Gecko Tools is fundamentally broken in this new version though.
