### ISSUE TITLE
[Enhancement] [Mechanic] [Gameplay] Square mode for private groups.

### ISSUE THREAD

**Issue by NugaSausage** [tagpro-game/tagpro-issues#123]
Please.

---

That's how serious this proposal is; I'm not using the short hand form of "please". Square mode was magical, and letting the community relive this wonderful moment will be absolutely fantastic. Plus, this is not like zombies (Halloween) or Egg Chase (Easter) where those unique events correspond with their respective holidays and therefore can only occur on their respective holidays; this event can correspond with any occasion, whenever the mood fits it, and it is not just limited to April Fools, so I feel this proposal has some merit. 

So again, to the wonderful developers that I'm not just sucking up to, from a Some Ball, please. 

(:

**Comment by Nick-Riggs** [comment]
It's unlikely that we will enable events as game modes. They simply become too much work to maintain over time.

**Comment by NugaSausage** [comment]
Thanks for explaining though~ :)
