### ISSUE TITLE
[Gameplay] Allow DCs within 30 seconds, or even shorter, on throwback maps.

### ISSUE THREAD

**Issue by NugaSausage** [tagpro-game/tagpro-issues#124]
This [Suggestion] post came from dogger and reddit.

(http://www.reddit.com/r/TagPro/comments/2tnh86/suggestion_allow_dcs_within_30_seconds_on/)

---

Cause who wants to play the original Dumbbell, Rink, Lold, or Arena? Yes, they're a part of TagPro's history and such and people should play them at least once, but really, honestly there can be some bad maps, and I know from experience that lots of players would bitch and complain, on both teams, whenever we get those maps, and it boils down to 12 minute chasefests, or players intentionally throwing the game to end it, if they haven't disconnected already (and I don't like game throwing).

**Comment by Moosemaster21** [comment]
I would definitely support this. There's a reason these maps were retired - some of them are simply tedious and unenjoyable to play.

**Comment by I-mess-up** [comment]
Thirded -- several maps can be very hard to win without getting lucky in
your teammates.

**Comment by Nick-Riggs** [comment]
Sorry guys, there is no plans to do this.
