### ISSUE TITLE
[Ads] Get redirected to a malware site disguised as ad

### ISSUE THREAD

**Issue by supmahbruddah** [tagpro-game/tagpro-issues#128]
I've been getting this url after joining some games: https://softwareupdaterlp.com/campaign/islandmention2/?ID=trillmstrcpi2&sub=trillmstrcpi2&S2=wELDFEC1ODJADDRH046NUB3A

Is this something on my end or is this ad known to occur sometimes?

**Comment by I-mess-up** [comment]
Happened to me too.

**Comment by NewCompte** [comment]
Looks like it happens on other websites too :

http://www.neogaf.com/forum/showthread.php?t=981278

**Comment by Nick-Riggs** [comment]
Yeah this appears to be a virus. 

http://malwaretips.com/blogs/remove-softwareupdaterlp-com-virus/

**Comment by supmahbruddah** [comment]
No malware reported though.  Cisco AnyConnect Web Security showed no
signs.  AdwCleaner showed nothing.  CCleaner shows nothing.  MBAM scan
running.  I typically see this on firstrowsports and similar sites.  Have
never contracted adware from those ones either, so long as you close the ad
properly and quickly enough.

**Comment by Nick-Riggs** [comment]
Googling SoftwareUpdaterlp.com reveals a ton of information that indicates a local virus. However I added softwareupdaterlp.com to the blocked ads in Google ads just in case.

**Comment by I-mess-up** [comment]
inb4 SULTP

**Comment by supmahbruddah** [comment]
thx Lucky
