### ISSUE TITLE
[Modtools] Allow moderators to see deleted reports

### ISSUE THREAD

**Issue by mcgrogan91** [tagpro-game/tagpro-issues#130]
There is a current problem with mod tools, where we can either choose to remove a report and have all of its information gone forever, or we leave a false report on someones account so that we can see who reported them.  We're inclined to leave false reports on people records to make it easier to find people who false report.

It would be a much better solution to somehow distinguish between reports that have been removed and ones that have not.  This is for two reasons:

1. It no longer counts as one of the 8 reports to ban for the player the report is removed from.
2. It makes it clear that the report was considered false when looking at the reportee.  If we see a bunch of removed reports it increases the liklihood that they're abusing the report system.

**Comment by Nick-Riggs** [comment]
I like it.

**Comment by WitchTP** [comment]
Perhaps try adding an extra boolean field to the table holding report information that marks a report as active or inactive? Of course, that assumes the existence of such a table.
