### ISSUE TITLE
Do away with FC kissing

### ISSUE THREAD

**Issue by nrabins** [tagpro-game/tagpro-issues#132]
Rationale: Kissing feels lame as an FC and could be more tactical.

How to do this: Instead of FCs popping when they come into contact with each other, they blow apart as if they both had rolling bomb.

Benefits: The skill cap of FC/FC interactions becomes more than just go-for-kiss/avoid-kiss. With the explosion, you can attempt to murder the other FC while simultaneously trying to stay alive yourself. It becomes much more exciting and interactive when confronting the enemy FC.

Powerups would affect this (how exactly is up for debate). Here's one possibility: if you had rolling bomb, you would be immune from the explosion and you would pop the other FC. Your rolling bomb would be diffused as it is now. Tagpro and juke juice would behave as they do now (have no effect on the interaction).

To prevent turtling between two colluding FCs, there are two options I see: 
1. Have the blast that affects the FC not affect the other players. 
2. Have a time range within which additional contact between FCs results in a kiss.

I'm not sure if this game mechanic would translate well to pubs, but I can see it being a popular option in group play.

**Comment by JGibel** [comment]
Why wouldn't flagpro kill the other flag carrier?

I don't think this is a terrible idea, and would deserve to be play tested. To fix colluding flag carriers, a refactory period would be good. I don't like the idea tha tit doesn't affect other  players

**Comment by DaEvil1** [comment]
I think this could be very interesting. I think to fix colluding flag carriers, a refactory period of something like 10 seconds would make sense.

**Comment by rabbatypus** [comment]
Neat idea but I think it goes against the logic of the game:

1. Anybody can pop flag carriers.
2. Flag carriers count as anybody.
3. Flag carriers can pop opponent flag carriers.

"Kissing" is the most logically sound result of two flag carriers touching and would be less complicated.

**Comment by jufda** [comment]
As rabbatypus said, it goes against the logic of the game. I cannot see why we would change that logic. Anyway, I do agree it's an interesting idea, and could be fun to try. Maybe it could be used in a some sort of special event, they are a way of making exceptions to basic game mechanics.

**Comment by Nick-Riggs** [comment]
Some very interesting ideas, but we are happy with kissing functionality.
