### ISSUE TITLE
Bug: mouse clicks register at the wrong coordinate

### ISSUE THREAD

**Issue by JonathanDCohen** [tagpro-game/tagpro-issues#133]
Mouse clicks are registered as pretty far left of where they actually occured.

To reproduce:  head on to a map test server and put into the console

tagpro.renderer.stage.mousedown = function(c) { console.log(c); }

Click near the left side of the map.  The global coordinates should be (-10000, -10000), despite clicking on the map.

https://www.dropbox.com/s/9xil621we0175go/mouse_bug%20%2801%29.mp4?dl=0  demonstrates it as well

Trying the solution from https://github.com/GoodBoyDigital/pixi.js/issues/654 doesn't work as the [getLocalPosition function](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/InteractionData.js#L48) references teh global property which is bugged anyways

**Comment by RonSpawnson** [comment]
I've noticed this where I try to click to report someone and couldn't, and sometimes clicking to the side reports them just as BBQ shows in his video.
