### ISSUE TITLE
Address request for a privacy policy

### ISSUE THREAD

**Issue by steppin** [tagpro-game/tagpro-issues#135]
Ron Spawnson made the following request on [reddit](http://www.reddit.com/r/TagPro/comments/2v2la4/what_is_the_privacy_policy_terms_of_service/).
> 
> I haven't seen a privacy policy yet (unless I missed it). With recent data privacy violations being exposed every day, it is important that companies which collect our information be transparent on how it will be used and how it will not be used.
> 
> Here are some particular questions I had. I'm sure others may chime in with some questions of their own.
> 
> Why does TagPro need my gmail account? Is this a security concern? I'm aware open sourcing is being held back since server code exposes everyone's email addresses.
> 
> What is done with this information (is it sold or given to any third parties such as advertisers?)
> 
> What information does TagPro store about my account and how long is it retained?
> 
> Are there any analytics being collected about my usage of TagPro? What is the nature of these analytics? Is there any personally identifying information linked to them? Is there a way to opt out?
> 
> How long are chat logs retained?
> 
> These are the main questions I can think of off the top of my head. If one doesn't already exist could we think about creating an actual privacy policy so Koalabeast is transparant with how they promise to handle our data?

We should consider having a privacy policy explaining what data we store and how we intend to use it

**Comment by RonSpawnson** [comment]
Can I please have an update on this? Will this be addressed? These are valid concerns and now I'm learning you guys have access to more data than I realized, including names, email addresses, ip addresses, computer hardware information, browser information, a list of all plugins we have installed, and google analytics.

I'd like to point out you are violating the Google Analytics terms of service by not including a privacy policy while collecting analytics data about us:

"You will have and abide by an appropriate Privacy Policy and will comply with all applicable laws, policies, and regulations relating to the collection of information from Visitors. You must post a Privacy Policy and that Privacy Policy must provide notice of Your use of cookies that are used to collect data. You must disclose the use of Google Analytics, and how it collects and processes data. This can be done by displaying a prominent link to the site “How Google uses data when you use our partners' sites or apps”, (located at www.google.com/policies/privacy/partners/, or any other URL Google may provide from time to time). You must not circumvent any privacy features (e.g., an opt-out) that are part of the Service."

**Comment by Nick-Riggs** [comment]
We are working on one.

**Comment by RonSpawnson** [comment]
Thanks for the update!

**Comment by Nick-Riggs** [comment]
This is the Privacy Policy we'll be deploying to tagpro servers in the next hot patch.

https://docs.google.com/document/d/1yPGNGaHY5JNh1UGVmtMGz8cDZalgGoOMCNgjnKThpPo/edit?usp=sharing

**Comment by RonSpawnson** [comment]
Thanks Lucky, this looks great!
