### ISSUE TITLE
Option to disable pub autojoin

### ISSUE THREAD

**Issue by yuxshao** [tagpro-game/tagpro-issues#139]
It would be nice if there were a setting that made it so that after a game, we're sent to the title screen instead of the loading game screen.

**Comment by steppin** [comment]
is this really that useful though?  I'm just trying to understand, what would people do after they got to the homepage other than play again or quit?

**Comment by Nick-Riggs** [comment]
Some people asked for this after we made all disconnects count. The reasoning was sometimes they got put into a game and they didn't want to. However I don't think it matters as we have the 1 DC grace every 8 hours.
