### ISSUE TITLE
[Bug] Ball images not working?

### ISSUE THREAD

**Issue by kingat95** [tagpro-game/tagpro-issues#140]
![tagpro bug](https://cloud.githubusercontent.com/assets/10914958/6099736/8baa8bd4-afce-11e4-9644-1b8fba331d54.png)

All of the balls look like this. I have had the Tagpro Mod Manager extension for awhile with no bugs like this, it just started today. I tried disabling the extension and it didn't work. I also use userscripts but don't know how to go about fixing that if those are the cause.

**Comment by I-mess-up** [comment]
Your spin script is at fault. There is a new one somewhere on the subreddit, PM me at /u/I_mess_up if you can’t find it.




Not a bug.

**Comment by kingat95** [comment]
Alright, thanks a lot, I appreciate it.
