### ISSUE TITLE
Sync up the report options available from in-game with the report options available from mod tools

### ISSUE THREAD

**Issue by nrabins** [tagpro-game/tagpro-issues#145]
Abuse of report system is a biggie that I would like to see in game.

**Comment by NewCompte** [comment]
I don't think you can really see if a report is false in the flow of the game.

I usually don't ban people for abuse of report system after only one report.

**Comment by nrabins** [comment]
I would disagree, I think there are often instances where you would be able
to see a false report. What about where a player is reported for
offensive/spammy chat when they've said nothing? What about when a player's
name is reported as offensive when he/she is a someball?

And this is separate from banning. The information would be used to ask the
player about the report / issue a written warning. Establishing a dialog
with the player might go farther towards preventing the behavior in the
future than simply banning.

**Comment by NewCompte** [comment]
What about where a player is reported for
offensive/spammy chat when they've said nothing? What about when a player's
name is reported as offensive when he/she is a someball?

It could be team chat/ a misclick. I really don't want bans for abuse of report system possible from in game. "abuse of report system" is different from false report.
