### ISSUE TITLE
Allow mapmakers greater control over powerup type

### ISSUE THREAD

**Issue by nrabins** [tagpro-game/tagpro-issues#150]
As per this thread: http://www.reddit.com/r/TagPro/comments/2086t3/suggestion_allow_mapmakers_greater_control_over/

**Comment by tagprowreckn** [comment]
I don't like it.  While I like the idea of having more elements, I think that each element should behave in exactly the same way on every map.  I don't even like the ability to define custom portal cooldown times.

**Comment by Nick-Riggs** [comment]
I agree with @tagprowreckn. I tend to favor consistency also. 

However these types of features are great for the mini-game culture within TagPro. If we did add more flexibility, it would be mostly for them.
