### ISSUE TITLE
Scores/Times/Flags/Other Junk follow around a random ball on screen 

### ISSUE THREAD

**Issue by E-TagPro** [tagpro-game/tagpro-issues#151]
It seems to happen if I resize the screen or maybe switch windows as the game is starting. Might not be all the time. Example:

http://i.imgur.com/z7VHla6.png

It's kind of funny but pretty annoying.

**Comment by I-mess-up** [comment]
Gecko Tools

**Comment by E-TagPro** [comment]
Ah, of course. Thank you.

**Comment by I-mess-up** [comment]
And it happens when you resize the window.

**Comment by SomeBall-1** [comment]
@E-TagPro close this.

**Comment by E-TagPro** [comment]
Oh, sorry. I didn't know how to do this. 

This is closed now. Thanks everyone !
