### ISSUE TITLE
[Policy] Official game policy on cheating and userscripts.

### ISSUE THREAD

**Issue by NugaSausage** [tagpro-game/tagpro-issues#152]
DaEvil1's post. (http://www.reddit.com/r/TagPro/comments/2vvef8/we_need_a_clear_official_policy_on_userscripts/)

**Comment by NugaSausage** [comment]
Could be a small link or disclaimer on the TagPro.gg site (and even the TagPro wiki) somewhere.

**Comment by RonSpawnson** [comment]
I think a "Terms of Service" could effectively encapsulate these things. Many established players know that botting leads to a 3 (or 1) month ban. Is this officially codified anywhere so newer players or players who frequent the subreddit less can be made aware?
