### ISSUE TITLE
[Policy] Official terms of service and terms of privacy.

### ISSUE THREAD

**Issue by NugaSausage** [tagpro-game/tagpro-issues#153]
RonSpawnson's post. (http://www.reddit.com/r/TagPro/comments/2v2la4/what_is_the_privacy_policy_terms_of_service/)

**Comment by NugaSausage** [comment]
Could be a small link or disclaimer on the TagPro.gg site (and even the TagPro wiki) somewhere.

**Comment by steppin** [comment]
see #135

**Comment by NugaSausage** [comment]
Oops. mb; I tried looking but didn't find anything. 

Closing.
