### ISSUE TITLE
[Suggestion] When the flag carrier has tagpro, I think they should be able to see where balls on the other team are going to spawn

### ISSUE THREAD

**Issue by goodluckhavefun123** [tagpro-game/tagpro-issues#154]

**Comment by steppin** [comment]
this should already be true

**Comment by goodluckhavefun123** [comment]
yeah, ill take a screenshot

**Comment by goodluckhavefun123** [comment]
Never mind, it seems like it was just that game

**Comment by steppin** [comment]
what can happen i think is that if a ball starts spawning before you grab the flag, then you grab the flag with tagpro), you will not see that ball's spawn
