### ISSUE TITLE
Rendering issue with blue team boost.

### ISSUE THREAD

**Issue by CarlColglazier** [tagpro-game/tagpro-issues#155]
I have had this issue in several games recently, but it only seems to affect the blue team boost tile. 

![image](https://cloud.githubusercontent.com/assets/9517688/6312950/81aa5822-b95f-11e4-9b90-a14a386d2392.png)

As the screenshot shows, this tile is not being rendered properly. 

Other possibly relevant information: 
+ **Browser:** Google Chrome v40.0.2214.115
+ **Extensions/Userscripts:** None

**Comment by I-mess-up** [comment]
To confirm, you don’t use any texture pack installer like TagPro Mod Manager?

**Comment by CarlColglazier** [comment]
@I-mess-up I was using a spin script when this screenshot was taken, but I have replicated the issue multiple times with no textures or scripts.

**Comment by NewCompte** [comment]
It happened to me with the portal tile but never with the boost tile.
