### ISSUE TITLE
Strange and seemingly random key bindings.

### ISSUE THREAD

**Issue by CarlColglazier** [tagpro-game/tagpro-issues#156]
I was looking at the `tagpro.keys` object when I noted something I found rather strange: each of the movement keys (up, down, left, right) have three different keys mapped to them; however, while the arrow keys and WASD keys are right next to each other, the third keys are spread all over the keyboard.

For reference, here is a list of all the movement bindings in `tagpro.keys`:

+ Up
 + 38: Up arrow.
 + 87: W.
 + **119**: F8
+ Down
 + 40: Down arrow.
 + 83: S.
 + **115**: F4.
+ Left
 + 37: Left arrow.
 + 65: A.
 + **97**:  numpad 1.
+ Right
 + 39: Right arrow.
 + 68: D.
 + **100**: numpad 4.

I was under the impression that the numeric keypad could also be used to control movement, but that does not seem to be the case. In fact, what should make the ball go left on the numpad actually makes it go right!

**Comment by NewCompte** [comment]
These keys have been that way since the first tagpro beta. They seem to map with ascii codes for wasd:

http://www.ascii-code.com/

They could probably be safely removed.

**Comment by Nick-Riggs** [comment]
There was a time when the keyCode on FireFox was returning the ascii codes in some instances. That isn't the case anymore.
