### ISSUE TITLE
Transparent canvas option no longer works.

### ISSUE THREAD

**Issue by CarlColglazier** [tagpro-game/tagpro-issues#157]
[As this thread notes](http://redd.it/2v918t) the `tagpro.renderer.options.transparent` option currently has no effect.

**Comment by Nick-Riggs** [comment]
@AMorporkian thoughts on this?

**Comment by NewCompte** [comment]
It does have effect, but it seems hard to modify it with the right timing.

This worked for me when pasted in the console:

tagpro.ready(function () {
    var oldCanvas = $(tagpro.renderer.canvas);
    var newCanvas = $('<canvas id="viewport" width="1280" height="800"></canvas>');
    oldCanvas.after(newCanvas);
    oldCanvas.remove();
    tagpro.renderer.canvas = newCanvas.get(0);
    tagpro.renderer.options.transparent = true;
    tagpro.renderer.renderer = tagpro.renderer.createRenderer();
    tagpro.renderer.resizeAndCenterView();
    newCanvas.show();
});
