### ISSUE TITLE
Bug? Avast anti-virus blocks new Segment server

### ISSUE THREAD

**Issue by E-TagPro** [tagpro-game/tagpro-issues#159]
I know that Avast is quite popular so it's surprising that I haven't seen anyone else post this issue. Disabling the 'Web Shield' unblocks the server; however, adding an exception to 'http://tagpro-segment.koalabeast.com/*' and 'https://tagpro-segment.koalabeast.com/* does not unblock the server. Obviously, disabling Web Shield is not an ideal solution. 

I used to use Avast 2014 and updated to 2015--neither work. I've restarted my computer, cleared cache/cookies to no avail. I'm at a loss as to what to do, so I'm wondering if there's an issue at TagPro's end since all other servers continue to work normally.

Thanks!

**Comment by Nick-Riggs** [comment]
We are aware of this. The IP address that was assigned to Segment was previously black listed by Avast sometime in the past. So it's a false positive. I've reported this issue to Avast, and I've asked for a new IP Address for Segment.
