### ISSUE TITLE
[Suggestion] [Mechanic] Ability to rate maps in private groups.

### ISSUE THREAD

**Issue by NugaSausage** [tagpro-game/tagpro-issues#160]
I'm sure this may not be such a good idea, but this beats one of my older alternate ideas of rating maps on the TagPro maps screen.

Currently, we can't (or at least every time I tried; not sure about others but I'm sure it's the same).

**Comment by NugaSausage** [comment]
As long as we can play a legitimate game in the private group (whatever constitutes that, like not ending too fast, or 10 minutes, or so forth), we can rate it, can we not?

**Comment by Nick-Riggs** [comment]
Enables users to easily rig the system by opening up a lot of browsers or getting groups of friends.

**Comment by NugaSausage** [comment]
True

**Comment by NugaSausage** [comment]
Can we at least have a throwback weekend every month, or every two months, to allow us to vote (or change our vote) on the older and retired maps?

**Comment by Nick-Riggs** [comment]
That's an MTC issue. You'll need to take it up with them.
