### ISSUE TITLE
Firefox freezes since a recent update.

### ISSUE THREAD

**Issue by NewCompte** [tagpro-game/tagpro-issues#162]
http://www.reddit.com/r/TagPro/comments/2xtaie/odd_not_black_screen_issue_firefox/

http://www.reddit.com/r/TagPro/comments/2xtaie/odd_not_black_screen_issue_firefox/cp3im6h

http://www.reddit.com/r/TagPro/comments/2xt1w5/having_black_screen_issues_come_test_a_fix_on/cp3k1p1

**Comment by Nick-Riggs** [comment]
I played on FireFox 36 for a few games last night and it ran great. Can anyone consistently reproduce this?

If it's freezing up FireFox, it's likely nothing to do with us directly and something more low level, like graphics drivers.
