### ISSUE TITLE
Remove the option to report Some Balls for offensive name.

### ISSUE THREAD

**Issue by I-mess-up** [tagpro-game/tagpro-issues#165]
http://www.reddit.com/r/TagPro/comments/2xvae6/suggestion_fix_this_i_was_playing_as_a_someball/

An assigned name cannot be offensive.

**Comment by Nick-Riggs** [comment]
Sounds like a good way to catch people who are abusing the report system. I'll consider it a "feature". :)

**Comment by I-mess-up** [comment]
Haha, just like large spectator flags :P

**Comment by NugaSausage** [comment]
Okay Nick-Riggs, how about we keep the ability to report Some Balls for offensive names (catch vote abusers) BUT they don't count towards the Some Ball (assuming they are a real Some Ball) so they don't get an unjust waiting period. 

Compromise, or just a mountain out of a mole hill?
