### ISSUE TITLE
Clearly define what is and is not bannable via a highly visible policy. 

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#166]
New players are getting banned, but aren't clear on what is causing it due to a lack of terms of service or generally visible rules.

http://www.reddit.com/r/nosleep/comments/2y3jdv/i_never_should_have_played_this_game/cp5zsn4
http://www.reddit.com/r/TagPro/comments/2y7f32/enthusiastic_new_players_saddened_by_confusing/

We should clearly define what can get a player banned and make it visible for new players. Sorry, that's pretty abstract, but this would be good to address before we consider any major pushes (Kongregate)

**Comment by Nick-Riggs** [comment]
We'll consider making "official rules", but they won't clearly be defined - at least not in a stringent way. It's important to me that moderators have leeway. If you define stringent rules, trolls tend to ride the line like a two year old pushing boundaries - then call foul when they receive a ban. 

Wrongful moderator bans happen, but they are pretty rare. Most bans are still issued by the community and the moderators ban those we catch abusing the system. It's not a perfect system, but overall I'm happy with it.

**Comment by RonSpawnson** [comment]
Good point lucky. I think the new players are getting banned for things they don't know are bannable, so maybe even showing them the report categories would be good. 

Although now that I think about it, when you are reported for violating a rule you see what the rule is. So maybe this isn't as necessary as I thought.
