### ISSUE TITLE
Allow players to turn off splat fading

### ISSUE THREAD

**Issue by nrabins** [tagpro-game/tagpro-issues#168]
I've heard that others were interested in this as well.

The new splat fading is neat for beginning players who might be using the vanilla texture pack and therefore have a harder time seeing spikes, but I'd like the option to let the splats accumulate near spikes. It leads to a neat aesthetic by the end of the game.

**Comment by NugaSausage** [comment]
Agreed; yes it's helpful for newer players, but it would be nice to toggle it, so i can see which spikes players fall victim to, or how many flaccids near base have occurred; just cause I want to see them.

Before this, the splats were there near the important tiles, but they "cut off" on the actual tile in question nearby (spuike, flag, etc.), so maybe it can work like that.

**Comment by NewCompte** [comment]
Agreed, I will try to convince Lucky on this. (Currently we can disable fading splats through userscript, but you can't bring back fading splats that were there before you entered the game.)
