### ISSUE TITLE
[Suggestion] [User Interface] Warnings to general public that disconnects via AFK counts as a report.

### ISSUE THREAD

**Issue by NugaSausage** [tagpro-game/tagpro-issues#169]
Newer players/Some Balls can fall victim to this (IRC messaging with turtlemansam and another player yesterday; plus this isn't common knowledge to those that don't use reddit/know the community and its goings-on).

A warning somewhere would be nice.

**Comment by NewCompte** [comment]
Done a month ago, you get warned after the report.
