### ISSUE TITLE
[Bug] the API for tagpro.socket.on('p') is inconsistent from test servers to main servers

### ISSUE THREAD

**Issue by JonathanDCohen** [tagpro-game/tagpro-issues#170]
Here is what the event looks like on Origin: http://puu.sh/gvkFl/b5068e1807.jpg  it has no timestamp and indexed events per player

Here is what it looks like on both maptest and newcompte's server: http://puu.sh/gvkKw/2c6428e376.jpg  It has a timestamp and an array 'u' indexed per player.  

One of these two needs to become standard across all servers.

**Comment by RondingTagPro** [comment]
As far as I know it depends on the type of message, e.g. the first message when somebody joins is not timestamped, in-game actions are timestamped except for the winning capture.

**Comment by NewCompte** [comment]
On my servers all messages are timestamped. Only some of them are on production servers.
