### ISSUE TITLE
[Suggestion] 1-D walls

### ISSUE THREAD

**Issue by Kublai-Khan** [tagpro-game/tagpro-issues#171]
Pretty self explanatory. Add a new wall type that would be a thin line allowing for more space in smaller/tighter maps. The way I'd envision it working is 6 different walls. 4 with the wall on each edge and 2 diagonal walls going through the middle. The only Problem I could see would be their visibility. This could be solved by highlighting the ground slightly under the walls.

**Comment by ylambda** [comment]
Your suggestion has merit, but I don't think this will happen. I see a broader issue being the limitation of using 1 pixel in map.png to determine the shape of a tile which accounts for a 40px space.
