### ISSUE TITLE
[Suggestion] Ramps and Multiple floors in normal gamemode.

### ISSUE THREAD

**Issue by Kublai-Khan** [tagpro-game/tagpro-issues#172]
Add a tile that acts as a ramp if you roll the right way up it you get to jump over other balls and most interestingly walls and spikes (You could have jumpable and non-jumpable walls).If you don't go quickly enough the ball would roll down again. This would require some kind of indicator of height as obviously tagpro is in a 2D frame of reference. This could be done by increasing the size of balls slightly with increased height to indicate movement towards the observer. Also maybe change the colour of the ball at the same time smoothly to a lighter shade (due to lighting maybe ?). Pseudo-3D maps would be so cool. In fact you could have maps with multiple floors by having multiple png files and the floors would be slightly transparent so that you can see parts underneath. It would also be cool if you fell into the black area/void you shrink till you pop.

**Comment by Nick-Riggs** [comment]
It's been discussed and we like the simplicity of not having a z-axis in TagPro.

**Comment by Kublai-Khan** [comment]
Instead of doing things in 3D then you could have ramps that act as a force in one direction so it would slow you deccelarate the ball in one direction and accelerate in the other. You could call it a magnetic field tile or something.
