### ISSUE TITLE
Enable caching of static assets

### ISSUE THREAD

**Issue by boraca** [tagpro-game/tagpro-issues#173]
Currently all static files that I checked are sent with max_age=0, which means that browser should download them every time. Could it be set to something like a month for music and maybe 2 weeks for graphical assets?

**Comment by Nick-Riggs** [comment]
Weird, this has changed recently. I'm not sure what caused this.

**Comment by Nick-Riggs** [comment]
I'm only finding that the current Chrome Stable isn't caching as expected. Other browsers and other versions of Chrome are. Can you verify?

**Comment by Nick-Riggs** [comment]
Actually that was a false positive - I had caching disabled in my browser for development purposes and forgot. It's working as expected. 

We are using etags to control caching. So max-age zero and no-cache is fine. You should be getting 304s on static content.

**Comment by boraca** [comment]
1. I'm always getting a 200 response, except for google ads and analytics. This is on chord, latest firefox, Win 8.1 x64. 
2. Etags serve a different purpose than Cache Control. With proper caching settings the browser won't even request the resource if it's newer than max-age. With Etags the browser requests the resource but if the server sees the same Etag it will respond with 304.
See:
http://stackoverflow.com/questions/499966/etag-vs-header-expires

**Comment by boraca** [comment]
I think that this one can be closed, now that caching is improved with 3.2
