### ISSUE TITLE
[Suggestion] Extend/get rid of auto-afk kick when player is on button

### ISSUE THREAD

**Issue by banzaiTP** [tagpro-game/tagpro-issues#174]
I've had this happen on Danger Zone, Hurricane, etc. Maps where you're playing D and sitting on the button. Just happened to me again.

Often times on certain maps, if I'm playing with a competent defender, I'll hang out on the button if there's only one (or no one) in base. One defender guarding flag, the other protecting against incoming boosts, etc. Several times, I've been kicked from the game for AFK. I'm not AFK. There's just no reason for me to be moving lol. 

It would be useful in general, I guess, if some sort of 5 second afk countdown timer always appeared, but I'd imagine that would be more work. So I'm not trying to ask for a huge fix. (Of course, maybe this is a huge undertaking, in which case, don't worry about it.)

It's just that it's surprisingly easy in pubs to not have to get off the button for a while, so it can be frustrating to be doing something useful and get a DC. I know it's an easy enough "fix" to just keep moving, but that's a bit frustrating because sometimes there's no reason to move.

Thanks :-)

Edit: I know I can move around, and it's been mentioned to me that I can also hit the space bar. I guess my response would be that I think asking a player to do something outside of normal gameplay in this scenario isn't the best solution. I know many ideas/suggestions are ruined by the fact that they could somehow be abused. But I can't imagine much abuse with this, because it would be very difficult to lag out/go afk and maintain your position on a button (a one tile space) for very long.

**Comment by Nick-Riggs** [comment]
It might be worth giving a 5 second warning of some kind for any AFK. I'll consider it.
