### ISSUE TITLE
[Suggestion] Flair when not under reserve name

### ISSUE THREAD

**Issue by ggodfrey** [tagpro-game/tagpro-issues#175]
Soon after I registered with TagPro, I changed the name displayed, and never changed back to my reserve name. Now, I'm 43° and I'd like to use flairs. I remember [luckyspammer saying he would bring it up with other devs](http://us.reddit.com/r/TagPro/comments/2v8s9z/why_cant_unregister_named_players_use_flairs/) but i haven't seen anything come of it. Will this be changed since there's more than just leaderboard flairs now?

**Comment by I-mess-up** [comment]
Just FYI you can change your reserved name to match your displayed name.

**Comment by NewCompte** [comment]
I think LuckySpammer would like that setting.

**Comment by Nick-Riggs** [comment]
This has been implemented. You can still turn flair off by selecting a single flair twice.
