### ISSUE TITLE
[Bug] Significant audio delay on Safari

### ISSUE THREAD

**Issue by raven-pride** [tagpro-game/tagpro-issues#179]
Title pretty much sums it up. More details here: http://www.reddit.com/r/TagPro/comments/2zvtlx/tagpro_sound_out_of_sync/

**Comment by NewCompte** [comment]
Some recent version of safari on Mac started attempting to consider all game sound files as being streamed. It caused issues and we were close to do something that would cut the sound for those users. We might do it in the future.

**Comment by Nick-Riggs** [comment]
This has been resolved - it was fixed by the browser maker.
