### ISSUE TITLE
Can't Appeal Bans When Banned

### ISSUE THREAD

**Issue by rabbatypus** [tagpro-game/tagpro-issues#180]
This isn't an issue for me, but there are always posts like this on the subreddit. The current system of posting on the subreddit and waiting for a mod to say "pm me the details and I'll fix that for you" is really inconvenient. The appeals page should be fixed.

**Comment by Nick-Riggs** [comment]
I believe @AMorporkian addressed this last week. This must be something new. We'll need to gather more details.

**Comment by Nick-Riggs** [comment]
This has been resolved.
