### ISSUE TITLE
Arrow keys should change cursor position in chat

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#182]
I'd like to propose the arrow keys can be used to change the cursor position in chat. I can use my mouse to change the cursor position, but then I cannot further dial it in any further.

The game context is already out of focus so I see no reason not to support arrow keys to change the cursor position in chat.

**Comment by AMorporkian** [comment]
We can only have one or the other. I'll lay the gauntlet down with the other devs. We'll have chat working as everyone expects one way or another by next patch.
