### ISSUE TITLE
All games over 30 seconds should count

### ISSUE THREAD

**Issue by goodluckhavefun123** [tagpro-game/tagpro-issues#183]
I know that some games do no count if the game determines the other team as "bad." What I am proposing is that all games over 30 seconds count, even ones where your opponents play badly. I feel like if you won, you deserve it, and just because you dominated your opponents, doesn't mean the win should not count.

**Comment by Nick-Riggs** [comment]
This is very close to how it will work in the next patch.

**Comment by goodluckhavefun123** [comment]
Is the patch this:  http://www.reddit.com/r/TagPro/comments/309m6d/in_test_win_flair_rolling_300_stat_timeframe/

Or will it come later?

**Comment by Aero2588** [comment]
Does this seriously mean that we are getting rid of the bad opponents rule? From this thread: http://www.reddit.com/r/TagPro/comments/2vbl2z/whats_the_logic_behind_not_giving_rank_points_for/

**Comment by goodluckhavefun123** [comment]
I believe so

**Comment by NewCompte** [comment]
Seems like we fixed this.
