### ISSUE TITLE
Space bar events in chat should count as no-op to avoid AFK kick

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#184]
Self explanatory via title.

See discussion in this thread: http://www.reddit.com/r/TagPro/comments/30ankb/please_please_please_add_a_disconnect_countdown/

**Comment by goodluckhavefun123** [comment]
I believe they are supposed to. At least, I was told they do.

**Comment by RonSpawnson** [comment]
I've noticed they don't, as have many others in the thread I linked. If you experience anything different please update this thread.
