### ISSUE TITLE
Provide a warning/indication a player is about to get kicked (timer) or at least notify the player why they got kicked

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#185]
If we are going to auto kick and autoreport, the system should do one or more of the following:

1. Warn the player that they have been detected to be AFK and will be kicked if they do not move
2. After kicking the player, give them indication why they were kicked and notify them a report was generated.

I understand this is intuitive to you and I, but this is not obvious to newer or less experienced players.

**Comment by NewCompte** [comment]
2. was done.

1. is controversial because we don't want to see players to be able to be actually afk a full game by moving precisely every 30s ( trolls + people who think what they have to say is more important,than playing might do that)

**Comment by RonSpawnson** [comment]
I don't think #1 was done at the time of ticket creation. Thanks for adding
that at least. Now when players get kicked because of AFK at least it's
obvious why they were kicked so they can avoid it in the future.

**Comment by I-mess-up** [comment]
I think you have your numbers backwards, but yeah.

**Comment by Mqrius** [comment]
@NewCompte
There are legitimate uses to standing still. The ones I personally encountered so far:
- Standing on regrab when nothing is going on.
- Hiding in a corner hoping they won't find you in zombie mode.

Now, of course, one can keep on wiggling, but then the only reason to wiggle is to avoid being auto-kicked, which is a mechanism that's supposed to be outside of the normal playing behavior.

Your counterpoint of "we don't want to see players to be able to be actually afk a full game by moving precisely every 30s" is true, but having no notification does not actually help against trolls, and only marginally against people chatting all the time. The more natural way to deal with trolls is user reports.

I have been kicked three times so far while playing the game as intended, so I feel not having a notification is hurting more than it supposedly brings. I would love it if you could reconsider not having a notification.
