### ISSUE TITLE
[Enhancement] Allow players to see how many reports they have against them in the last 24 hours

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#186]
I would like the ability for players to see how many reports they have against them. 

Either this could be done on the profile page or similar, or the "you got reported" message could append the number of reports. Ex: "Someone reported you for working against own team. You have 3 reports today".

**Comment by goodluckhavefun123** [comment]
You could always use this script: http://www.reddit.com/r/TagPro/comments/2c3yv4/userscript_show_the_number_of_daily_reports/

**Comment by RonSpawnson** [comment]
Thanks! I also am officially requesting this be implemented in the game. I think all players should be able to see how many reports they have against them.

**Comment by I-mess-up** [comment]
AFAIK That script only shows reports given to you that you saw in game chat. It wouldn’t show reports from going afk and it wouldn’t show reports given while playing on another computer. It’s really pretty half-baked (through no fault of whoever wrote it) because a report count isn’t integrated into Tagpro.

**Comment by NewCompte** [comment]
I am not convinced this is something we should share with players.

I don't want players to make just the amount of trolling that gets them 7 reports but not 8.
I like the fact that players don't exactly know when they are going to be banned.

**Comment by Nick-Riggs** [comment]
I agree with @NewCompte, this would become an effective way for trolls to dodge bans.
