### ISSUE TITLE
Clicking on a player's ball does not always bring up the report dialog

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#187]
I think something is wrong with the mouse location detection. Clicking on the ball does not always bring up the report dialog. 

I've tested in Chrome.

**Comment by NewCompte** [comment]
Do you know when it works and when it doesn't ?

**Comment by RonSpawnson** [comment]
Here you go NewCompte: https://www.youtube.com/watch?v=3HHcGfN6KyE

I am demoing a couple of the reporting bugs I have seen, and it looks like I stumbled upon reproducible conditions. It has something to do with the player's position relative to the position of the player they are clicking on. Watch the video for specific details.

**Comment by NewCompte** [comment]
Is it exactly when the ball to report is in this area:

http://i.imgur.com/nLDEh0V.png

?

Looks like the chat history div is making the clicks to report not work.
