### ISSUE TITLE
[Suggestion] New Favicon & Different Favicon When in Game

### ISSUE THREAD

**Issue by MrJoehobo** [tagpro-game/tagpro-issues#189]
So right now the current favicon doesn't have anything to do with TagPro. And if the favicon changed color when you got put into a game, it would be an easy way for someone to realize the game started if they were in a different tab. Personaly I started using a blue flag http://puu.sh/bUGcH/b7145d087e.png for  koalabeast.com.(everything besides games) And a red flag i.imgur.com/FWPzuEZ.jpg for koalabest.com:(ingame)

**Comment by RonSpawnson** [comment]
+1, I think a favicon for TagPro specifically would be sweet.

**Comment by NewCompte** [comment]
Our current favicon is:

https://github.com/senchalabs/connect/blob/2.x/lib/public/favicon.ico

It would be smart to change.

**Comment by Nick-Riggs** [comment]
This has been implemented.
