### ISSUE TITLE
Show tenths of seconds in last minute

### ISSUE THREAD

**Issue by AMorporkian** [tagpro-game/tagpro-issues#19]
In the last minute of a game, tenths of seconds show up in game clock

**Comment by jufda** [comment]
There's no point to have it only for the last second. I personally would like us to have it toggleable (maybe with an option to choose where it starts to show tenths if at all). I used the beforementioned script to show tenths for the whole game, until tagpro update that broke it for me (I kept getting few a few seconds long lagspikes when the whole game did froze when I had the script enabled). The timer does now have a little black border and it's a bit transparent, which is great.

**Comment by Nick-Riggs** [comment]
Marked as won't fix but we are doing this in TagPro next - at least the last 5 seconds.
