### ISSUE TITLE
New Movement Keys?

### ISSUE THREAD

**Issue by BlueDev94** [tagpro-game/tagpro-issues#190]
Hi, I have currently run into the problem of non functional keys on my laptop and only source of internet connection. Both the arrow keys and wasd have lost a full set of mobility and I'm not really sure what to do. I have no idea how tagpro code works but how hard is it to add something like IJKL into the game? I also people who have things mapped to keys all the time and is it possible to map movement to anything?

**Comment by banzaiTP** [comment]
There is a user script that allows you to change the keys you use. As far as I know, it still works. (I haven't used it, I just remembered seeing it.)

http://www.reddit.com/r/TagPro/comments/2n7sdq/userscript_remap_your_keys/

Hopefully that helps.

**Comment by BlueDev94** [comment]
Do you mind linking me to a thread that tells me how to download and use the script? I can't seem to figure it out. I have Chrome.

**Comment by banzaiTP** [comment]
I can try to talk you through it, though I'm not a very valuable tech resource lol.

1. Install tampermonkey. (http://tampermonkey.net)
2. Once you have that installed, visit that comment I'd posted and click on the blue "Remap your Keys! Script" writing. That should bring you directly to a page that will allow you to install the script. But don't click install yet!
3. There will be a window at the bottom of the page with the script itself. Careful not to mess with it and add/delete anything by accident, but it's in that window you can simply edit what key does what. Again, see the original subreddit post for specifics on that.
4. Once you've set the keys the way you want, just click "Install." It should be up and running.

**Comment by BlueDev94** [comment]
Thanks a lot. I appreciate it. It works.

**Comment by NewCompte** [comment]
Fixed through userscript.

Setting keys should be a default feature in TagPro Next.
