### ISSUE TITLE
Wind Tunnels

### ISSUE THREAD

**Issue by 3volt** [tagpro-game/tagpro-issues#192]
http://www.reddit.com/r/TagPro/comments/312esh/suggestion_windtunnels_instead_of_black_holes/

**Comment by ylambda** [comment]
I'm not sure how to draw a wind tunnel on the map and provide meaning to a player about it's function. A conveyor belt might work better.

**Comment by 3volt** [comment]
Yes, that might work better, assuming the conveyor belt was constant.

**Comment by Nick-Riggs** [comment]
This won't be implemented into TagPro Classic.
