### ISSUE TITLE
Flag state not updated when in penalty 10 seconds

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#194]
Steps to reproduce:

1. Join a game
2. Refresh. This will cause you to have a 10 second penalty spawn.
3. During this spawn, if the flag is taken from your base it will still look like it is in your base. This happens until you spawn.

**Comment by Kublai-Khan** [comment]
This happens with anything that changes as far as I know whilst joining a game. I've seen it happen in the 3s as well with powerups and flags.

**Comment by I-mess-up** [comment]
Yep, even in the 3s I see boosts used that stay active until I spawn.

**Comment by RondingTagPro** [comment]
I also don't receive any map updates while waiting for my first spawn in any ongoing game. I haven't noticed any problems after popping and waiting for respawning.

**Comment by NewCompte** [comment]
I think I fixed this recently.

**Comment by RonSpawnson** [comment]
People are still noticing this issue according to the subreddit. Perhaps there is more involved?

http://www.reddit.com/r/TagPro/comments/34wjls/bug_graphic_glitch_flag_stays_and_appears_to_be/

"I have been getting the same error more often recently.
It appears like the game loaded normally, but a few seconds later, you can tell the graphics aren't working cause the in-game sounds play when there's a tag or a grab.
The flag is grabbed but it still appears to be in the base."

**Comment by NewCompte** [comment]
It doesn't seem to be linked to spawning though.

**Comment by RonSpawnson** [comment]
To me it seemed ambiguous. I'm asking them for clarification.

**Comment by RonSpawnson** [comment]
Confirmed, this seems to be a different issue reported in Reddit today. Maybe it's a userscript causing it? I've never experienced it myself.
