### ISSUE TITLE
Interactive tutorial for new players

### ISSUE THREAD

**Issue by ballparts** [tagpro-game/tagpro-issues#197]
See [this post](http://www.reddit.com/r/TagPro/comments/320kr0/suggestion_interactive_tutorial_for_some_balls/) on the sub.

**Comment by NewCompte** [comment]
Spinning up games for one player cause technical issues.

Maybe in tagpro.next ?

**Comment by Nick-Riggs** [comment]
It's pretty likely this will be in Next.

**Comment by ballparts** [comment]
Whoa, this seems like a lifetime ago. Cool to see you guys are working hard on Next.
