### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by RondingTagPro** [tagpro-game/tagpro-issues#198]
[As noted here](https://www.reddit.com/r/TagPro/comments/321ji3/plans_for_expansion/cq75r0d), search engines currently do not link TagPro to any keywords or description of the game. This makes it very unlikely that people searching for a fun game to play will find TagPro in their search results. Hence we get less new players than possible.

The solution is to include a textual description of the game, possibly supplemented with images, to the server selection page and the homepage of each server. This has the additional advantage that people immediately see what the game is about when they get linked to the game, rather than thinking "what server selection" and "play now what". I.e. the current homepages are primarily designed for returning players, the videos on the server selection page are the only elements oriented at new visitors yet videos are not indexable by search engines.

**Comment by I-mess-up** [comment]
This may or may not be related, but when I show new people the game they always search for “Tagpro centra” instead of typing in the address, and then they click on the first server, which is Radius.
