### ISSUE TITLE
[SUGGESTION] Get a signed site certificate 

### ISSUE THREAD

**Issue by supmahbruddah** [tagpro-game/tagpro-issues#199]
I've been getting the error that the browser cant load socket.io.js and I'm certain it's my companies' antivirus (Cisco AnyWeb blah blah).  I think it's due to the site not having a signed cert that it doesn't trust the source.  You can get free certs from StartSSL.  I've used them in the past and it works just fine and is generally recognized as a valid root authority.

**Comment by RondingTagPro** [comment]
Why? The game does not use HTTPS as far as I'm aware. I think it uses websockets on port 443, maybe that confuses your firewall.

**Comment by supmahbruddah** [comment]
Because it would likely resolve that confusion as far as I'm aware.

**Comment by supmahbruddah** [comment]
Curious, with this https://code.google.com/p/chromium/issues/detail?id=439797#c15 wouldn't upgrading to wss: alleviate the issue with more firewalls?

**Comment by Nick-Riggs** [comment]
We might move all the sites to SSL in the future but it isn't a priority.
