### ISSUE TITLE
Games start with 4 players minimum

### ISSUE THREAD

**Issue by AMorporkian** [tagpro-game/tagpro-issues#20]
Games don't start until each game is 2v2 at the least. They would sit in the waiting state until then.

**Comment by Snorge** [comment]
I think now that we have the Win % flair, it would be a very good idea to reconsider something like this.

Generally people have been pretty good about waiting during 2v1 or similar starts, but now that there is a Win % flair incentive, I have already noticed this courtesy declining.

**Comment by jufda** [comment]
Would it be possible to put 1-3 players to a warm-up game, let them roll around until 4th player joins, and reset everything, starting normal countdown to start the game. There could be a big "WARM UP" message, flags could be ungrabbable or something like that. It would give the players an opportunity to become more familiar with the map, and not get bored waiting, and make it harder to abuse 2vs1 situations.
