### ISSUE TITLE
[Possible Bug?] Tiles are still drawn under 45 degree walls

### ISSUE THREAD

**Issue by MrJoehobo** [tagpro-game/tagpro-issues#201]
I decided to make part of my <a href="http://i.imgur.com/OCIadMm.png">walls transparent</a> and it <a href="http://i.imgur.com/oeYLwa5.png">looks good</a>. But I noticed on 45 degree walls the <a href="http://i.imgur.com/A7PyU7A.png">tile is still rendered</a> under the <a href="http://i.imgur.com/yc1IOey.png">wall. </a>I was just wondering if this is something that can or will be changed, or if the current way is the way it has to be.

**Comment by SomeBall-1** [comment]
The floor is drawn under the 45 wall because there's still half the tile that isn't covered by the wall. This is on purpose and will likely not be changed.

**Comment by NewCompte** [comment]
It would be quite hard to change.
