### ISSUE TITLE
Spinning Visual Enhancement

### ISSUE THREAD

**Issue by nrabins** [tagpro-game/tagpro-issues#202]
It would be neat to have some sort of graphic for spinning in vanilla tagpro, since the spin physics do play a part in movement mechanics.

Also, when your ball is spinning rapidly and you hit a wall, it should kick up sparks in the appropriate direction, like this: http://us.123rf.com/450wm/fotomaximum/fotomaximum1407/fotomaximum140700225/30388125-worker-cutting-metal-with-grinder-sparks-while-grinding-iron.jpg

**Comment by NewCompte** [comment]
Unfortunately, spinning vanilla 3d-looking tagpro balls would be hard and not really good for other texturepacks.
