### ISSUE TITLE
[Bug] Clock enters negative numbers

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#203]
If a game ends and all time runs out, the clock goes to negative numbers. This looks unprofessional but should be a quick fix (check your bounds before deducting the clock past 0). 

If we can ever open source the game I'd be happy to submit a pull request to look into it further.

Picture demonstrating the bug: http://i.imgur.com/0zDiaZ7.jpg

**Comment by NewCompte** [comment]
I think this is the result of flooring instead of rounding the time left. We often get the the "end" socket when the client-side code is a few ms below 0.

**Comment by RonSpawnson** [comment]
Thanks for the response NewCYes, I was assuming something like this was happening.

Seems like my proposed solution of bounds checking on the client should be able to resolve this issue. After flooring the time left, you could check if it is less than 0 and if so, change it to zero.

**Comment by Nick-Riggs** [comment]
Duplicate: https://github.com/tagpro-game/tagpro-issues/issues/161
