### ISSUE TITLE
[Bug?] [Suggestion?]

### ISSUE THREAD

**Issue by goodluckhavefun123** [tagpro-game/tagpro-issues#204]
Some players get rank points (and the win) and others don't on the same team. We were all there from the beginning of the game. Why??
![screen shot 2015-04-18 at 10 39 48 pm](https://cloud.githubusercontent.com/assets/10569709/7217947/56f6fb8c-e61c-11e4-9ea6-ee4a1f43f078.png)

**Comment by NewCompte** [comment]
It should be fixed with 3.2.
