### ISSUE TITLE
[Feature suggestion] Kill feed

### ISSUE THREAD

**Issue by boraca** [tagpro-game/tagpro-issues#210]
I think it would be nice to have some information about how balls have died recently. Something like that: http://i.stack.imgur.com/bvlJq.jpg (right upper corner).

possible kill messages:

Someball spiked himself.
Someball popped by Someball2 with TagPro
Someball (Flagcarrier) kissed Someball2 (Flagcarrier)

and so on..

It could also include information about who scored.

**Comment by NewCompte** [comment]
It's already possible to do something like that through userscripts.
