### ISSUE TITLE
False DC's

### ISSUE THREAD

**Issue by ABigBall** [tagpro-game/tagpro-issues#211]
Okay for a while now i have been wondering where all my DC's have been coming from because i never leave games early or disconnect in any way, but i've just let it go because i don't really care about my win percentage usually, but recently i have been trying to get my rolling 300 to 55%, before i joined a game i looked and saw i was at 51% and if i win one more game i will get to 52%, i had 14 dc's in the rolling 300 so far, anyway, i won the next game and went to look at my stats again, and it was still at 51% and i now had 15 dc's, i did not leave the game until after we had won, i think this is where all my DC's are coming from and its unfair, i win the game, leave before i search for a new one and get a DC, i know for certain it's not supposed to be like this.

I've been playing the game for about a year now and have played in 3 competitive seasons so it's not like i'm new to the game and am doing something wrong, here is a link to my profile, please help:

http://tagpro-chord.koalabeast.com/profile/538334d16021393f65278cd5

A Big Ball.

**Comment by I-mess-up** [comment]
Do you ever get kicked for afk?

**Comment by Nick-Riggs** [comment]
In almost all of your DCs you are only connected for 5-20 seconds. You are quitting at the beginning of games. You can only do that once in a while for it not count as a DC.

**Comment by ABigBall** [comment]
why is that not told to people? that's a very obscure rule to have that you can only leave at the start of a game 'once in a while', i've always been told it doesnt count as a dc if you leave in the first 20 or 30 seconds, when did this change? and if it has always been like this, why do people not know about it? is there an exact amount you can do it, or is it literally as random as 'every once in a while'?

**Comment by I-mess-up** [comment]
Lucky might have been unclear. The rule is, you get 1 free DC in the first 30s of a game every 8 hours (3 per day if you space it out right).

**Comment by ABigBall** [comment]
so if you continuously get put into pubs where its just you and sometimes 1 other player you cant just leave? you HAVE to wait otherwise it effects your stats?

**Comment by Nick-Riggs** [comment]
This was changed a long time a go, and was stickied on the site for many days. 

No, you wouldn't get a DC if it was just you and a single Some Ball. The games you disconnected from (a lot), were viable games.

**Comment by ABigBall** [comment]
are you able to see what the most recent one was for? because that was the one that really confused me, just after I wont a game...

**Comment by Nick-Riggs** [comment]
Says you were only connected for 11 seconds.

**Comment by ABigBall** [comment]
i won a game on ricochet 3-1, oh well, at least i know the rules now, i know it seems far-fetched coming from just me, but maybe in Tagpro next, have a rule book or something on the actually tagpro.gg website, anyway, love the game, keep up the good work :) and thank you (both of you)

**Comment by I-mess-up** [comment]
I’ll second an official rulebook, and I”m sure the community would love to help write it.
