### ISSUE TITLE
find game broken

### ISSUE THREAD

**Issue by Rushwing19** [tagpro-game/tagpro-issues#212]
Not sure if this is the proper venue, but I'm not getting the feedback I need on reddit. For some reason when I click play game and am brought to the Find game page, it's blank except for the background. Does this on both chrome and safari and I even reinstalled chrome to no avail. Only things that i did that maybe could have caused this- replaced my hard drive (shouldn't be an issue). And scanned my computer for infections, deleting various infected files. Running on a mac OSx 10.9.5

**Comment by cfeio** [comment]
Do you have any userscripts installed?

**Comment by Nick-Riggs** [comment]
Bring up the JavaScript console: Cmd + Opt + J

Send us an errors you see.

**Comment by Rushwing19** [comment]
Hey! Thanks!
I went to the find game page and used the JavaScript console command
recommended. Here's what I got-

Failed to load resource: net::ERR_EMPTY_RESPONSE
global-findGame.js:1 Uncaught ReferenceError: io is not defined
http://www.google-analytics.com/analytics.js Failed to load resource:
net::ERR_BLOCKED_BY_CLIENT

Thanks again for your help :)

**Comment by Rushwing19** [comment]
I disabled avast and that got rid of the blocked by client error.

now it just says:
http://tagpro-radius.koalabeast.com:443/socket.io/socket.io.js Failed to
load resource: net::ERR_EMPTY_RESPONSE
global-findGame.js:1 Uncaught ReferenceError: io is not defined

**Comment by Nick-Riggs** [comment]
If you go to:

http://tagpro-radius.koalabeast.com:443/socket.io/socket.io.js 

What comes up?

**Comment by Rushwing19** [comment]
Theres a little page icon with a frown face. Then the text:No data received

ERR_EMPTY_RESPONSE

then under details it reads: Unable to load the webpage because the server
sent no data.

thats it, thanks. (scuze my caps)

**Comment by Nick-Riggs** [comment]
This is super strange. That resource is there - I have no idea why your browser is telling you it's not. And all your browsers say it's not there?

If all the browsers are saying it's not there. It's not the browsers, it's something on the computer or maybe a firewall/proxy you are connected to.

**Comment by Rushwing19** [comment]
Hmmmmm- It's the same with all browsers and a firewall/proxy situation
doesn't make a lot of sense to me. I was able to play the game fine for a
while and it occurs no matter where I'm connecting to the internet.
Honestly- it's a really fun game, but I'm prone to getting sucked in and
spending more time than I should, maybe it's just for the best. I really
appreciate your effort!

**Comment by Nick-Riggs** [comment]
It's probably something on your PC blocking - an over zealous virus protection or something to that effect.

**Comment by Rushwing19** [comment]
Hey got a fix- So I turned off the Avast extension for my chrome browser
and there was no extension for safari, though I was having the same problem
on safari. Turning off the extension made no difference for chrome.
Eventually I uninstalled avast from the computer and tried playing the
tagpro and presto- back to normal. Thanks for your help just thought I'd
let you know what happened.

**Comment by Nick-Riggs** [comment]
Thanks for letting us know - we've had problems with Avast in the past but Avast resolved them. I wonder if the issue is back.
