### ISSUE TITLE
[Bug] Rolling 300 registering neutral maps as CTF?

### ISSUE THREAD

**Issue by TPnazgul** [tagpro-game/tagpro-issues#213]
Everyone seems to have extraordinarily high ratios of CTF:neutral maps. Any idea why that might be? I haven't tested to see if a given map is counted wrong or something but I think something's up.

e.g. http://imgur.com/m1o3UYT

**Comment by NewCompte** [comment]
There are 23 maps in rotation right now, and only 5 of them are neutral flag maps.

5/23 = 21.7%
62/280 = 22.1%

pretty similar.

**Comment by TPnazgul** [comment]
Ah, yeah I guess I didn't look I the wiki closely enough. The current rotation isn't up to date.
