### ISSUE TITLE
Bitcoin Donation Error

### ISSUE THREAD

**Issue by chrahunt** [tagpro-game/tagpro-issues#214]
The bitcoin donation button does not work.

Steps to reproduce:
1. Click bitcoin donation button [here](http://tagpro-radius.koalabeast.com/donate).
2. See page with "Internal Server Error".

**Comment by NewCompte** [comment]
It happens all the time for some unknown reason. We know a temporary fix that we do every time but it doesn't last.

Thank for the report, I will look for a more permanent solution.

**Comment by chrahunt** [comment]
Thanks! Last time wasn't it information that needed to be submitted to Coinbase, or is this a different issue?

Threads to be updated, when fixed: [here](http://www.reddit.com/r/TagPro/comments/344cmg/hey_is_the_bitcoin_donation_link_broken/) and [here](http://www.reddit.com/r/TagPro/comments/3278du/trying_to_donate_via_bitcoin_just_gives_an/) .

**Comment by NewCompte** [comment]
It seems that I have a fix for having to make new keys every time. We will test it on Tangent soon.

**Comment by NewCompte** [comment]
It is in test on Tangent now.

**Comment by NewCompte** [comment]
It has been fixed.
