### ISSUE TITLE
[Suggestion] Add powerup shadows to vanilla texture

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#217]
Please see: http://www.reddit.com/r/TagPro/comments/36hqcl/suggestion_add_pup_shadows_to_vanilla/

**Comment by I-mess-up** [comment]
Can we have an update on this? Just a yes or a no? It is incredibly simple to implement as the game code already supports it. All that needs to be modified is a 40x40 pixel area in tiles.png.
