### ISSUE TITLE
Save percentage shows as - when it should be 0

### ISSUE THREAD

**Issue by jochakovsky** [tagpro-game/tagpro-issues#219]
If you have zero saves and more than zero attempts, the save percentage should be 0. Instead, it shows up as -, as if you have no save attempts. Screenshot attached. Thanks!

![screenshot 2015-05-21 23 57 38](https://cloud.githubusercontent.com/assets/12554493/7763853/4d04c0ec-0015-11e5-9905-f344ac2fa097.png)

**Comment by TPsquirrely** [comment]
That's just how 0 % shows. If you lose your first game of the day you'll see the same thing.
