### ISSUE TITLE
45 degree gates

### ISSUE THREAD

**Issue by AMorporkian** [tagpro-game/tagpro-issues#22]
Similar to 45 degree wals

**Comment by DaEvil1** [comment]
It would definitely be more than aesthetically used. assuming they function like actual 45 degree gates. It's not something I'd say should be a top priority, but I think a lot of mapmakers would agree that it would be a "nice to have" feature.

**Comment by jufda** [comment]
Not high priority, but would make perfect sense to have them now that we have 45 degree walls. They would probably even be used in ways that actually affect gameplay, like in speed run maps that require pixel-perfect skills or something like that.
