### ISSUE TITLE
Possible Unregistered Save Attempt Repro

### ISSUE THREAD

**Issue by YankTagpro** [tagpro-game/tagpro-issues#220]
Here are the steps I followed.

1. Stats turned off.
2. Joined a game as it was ending. It ended in a loss for my team ~10 seconds after joining.
3. Turn on stats in another tab.
4. Get placed into another game down 2-0.
5. Notice that there's no Save Attempt text.
6. Lose after a minute and see the loss registered.

I didn't disrupt the joiner loop between the two games, so the second game should not have been recorded as a loss, correct?

**Comment by Nick-Riggs** [comment]
If it can be duplicated, we'll look into this. But this turning stats on/off thing in another tab seems sketchy - not sure why players would be doing this.
