### ISSUE TITLE
[Suggestion] Some cosmetic improvements to the flair page

### ISSUE THREAD

**Issue by TagProKrieger** [tagpro-game/tagpro-issues#222]
Apologies if it's bad form to include multiple suggestions within one issue, but I felt uncomfortable with spamming three very minor and similar things in a row.

1. **Change "TagPro Developer" to "Developer".** It seems kind of silly to me that the word "TagPro" is arbitrarily used in the developer flair but not the moderator flair. There should be a convention for this, but appending "TagPro" to every flair *might* just be a little ridiculous -- I'd rather remove it altogether, and there wouldn't be any meaning lost.
2. **Move the Community Contest Winner flair with the other flairs up top.** This and the Developer, Community Contributor, and Moderator flairs are given to recognize involvement in the community and contribution to the game, yet for some reason one is separated from the rest and awkwardly sandwiched in between the donor and leaderboard winner flairs. It'd be really great if it could be moved below the Moderator flair.
3. **Sort the leaderboard and win rate flairs in ascending order.** Currently, these are shown from hardest to easiest, but the donor and degree flairs are shown from easiest to hardest. Perhaps it doesn't *have* to be in ascending order, but I'd like to have a consistent convention and this seems like it would be more accessible to new players than the alternative.

**Comment by steppin** [comment]
I think these are all solid ideas

**Comment by steppin** [comment]
thanks for the suggestions; we'll likely push the changes on the next update!

**Comment by TagProKrieger** [comment]
Sweet! Thanks for taking them!

**Comment by TagProKrieger** [comment]
It's been over 5 months since this conversation was closed. Can I get an update on this?
