### ISSUE TITLE
Bug - No Flag in Neutral Flag

### ISSUE THREAD

**Issue by oscarluke** [tagpro-game/tagpro-issues#224]
Ricochet on Origin

I joined late, seems like FC may have quit.

![screen shot 2015-05-26 at 8 58 59 pm](https://cloud.githubusercontent.com/assets/3410080/7826587/2b26b286-03ea-11e5-8d18-ec2dea27d06a.png)

**Comment by Nick-Riggs** [comment]
Closing this for now because while I think it is a bug, it seems to be crazy rare.
