### ISSUE TITLE
[Bug] Player leaving team in private group switched away from center view

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#225]
I was watching a private group game centered (like we usually do when streaming a game). A player left the game (lagged out) and that caused the camera to switch from centered to directly on a specific player.

Expected behavior would be if a player chose specifically to hit 'c' to center the cam, it shouldn't uncenter until the player specifically asks it to.

**Comment by NewCompte** [comment]
I have made some code to fix this.
