### ISSUE TITLE
Save attempt eligibility is easily circumvented. Proposed change in logic

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#227]
While the logic behind what qualifies a save attempt was purposefully hidden from us, it has become common knowledge that joining through the "Play now" button makes you ineligible for a save attempt.

As eluded to in this post: http://www.reddit.com/r/TagPro/comments/37k101/sadboys_guide_to_win_pubs/ it's easy to circumvent this by playing the first game with stats off. This could allow someone to game the system in always having a chance at a save attempt every game.

I propose the logic can be updated such that if the game is the player's first game with stats on it is ineligible for the save attempt.

**Comment by RonSpawnson** [comment]
This of course depends on what your intentions are of limiting the first game attempt. Just wanted to make sure you were aware people are circumventing it and wanted to offer a possible alternative to close this possibility.

**Comment by NewCompte** [comment]
I think this is OK to do. Our intention in limiting the first game attempt is to prevent people save-shopping by joining at the right time.

**Comment by RonSpawnson** [comment]
Sounds good. Closing the issue
