### ISSUE TITLE
[Suggestion] Volume control in game

### ISSUE THREAD

**Issue by TheLetterJ** [tagpro-game/tagpro-issues#228]
Currently users can only mute game music and sound or have it at full volume.  Control over the volume would be a really nice feature, especially for those of us that like to listen to our own music.  Having the ability to properly mix our own music, OS sounds, etc. with the TagPro sound and music would be a much better experience.

**Comment by RonSpawnson** [comment]
Your OS may be able to do this already. What OS do you have?
