### ISSUE TITLE
[Suggestion] Full support for retina displays

### ISSUE THREAD

**Issue by jochakovsky** [tagpro-game/tagpro-issues#231]
TagPro would look a lot nicer and less blurry on retina displays (for example, the retina MacBook Pro) if it had high-resolution sprites, etc. It seems like a site's CSS can be modified to serve different images depending on the device's pixel density - see http://www.html5rocks.com/en/mobile/high-dpi/ for more info.

**Comment by I-mess-up** [comment]
I’d love this.
