### ISSUE TITLE
[Suggestion] Exit button/link on joiner screen

### ISSUE THREAD

**Issue by dddeeefff** [tagpro-game/tagpro-issues#233]
If I finish a game, am taken to the joiner and want to stop playing, there is currently no way on the tagpro interface to stop joining a game. I think there should be.

Page I am talking about: http://tagpro-[SERVER].koalabeast.com/games/find/

**Comment by I-mess-up** [comment]
I agree that there should be an obvious exit button but I’d like to let you know that the Tagpro logo at the top serves as a link to the home page.
