### ISSUE TITLE
[Suggestion] Twitch/Streaming flair

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#234]
http://www.reddit.com/r/TagPro/comments/3821s6/flair_suggestion_twitch_flair_for_regular/

**Comment by NewCompte** [comment]
The main criteria for new flairs is how easily I can get them. I don't know how to stream, :-1: .

**Comment by RonSpawnson** [comment]
You are in luck, the Spawnson Streaming Guide is just the thing for you!
