### ISSUE TITLE
tagpro's banned page needs to update its report options

### ISSUE THREAD

**Issue by MultiMediaWIll** [tagpro-game/tagpro-issues#235]
http://tagpro-origin.koalabeast.com/banned

"Nope, I just checked and you're definitely not banned.
Be respectful of other players and you'll be just fine.
Here are some common reasons people get banned:

offensive name
offensive or spammy chat
working against own team
afk too much
chat harassment"

Those are the old report options.

**Comment by NewCompte** [comment]
Fixed, but we also removed them form the /banned page.
