### ISSUE TITLE
[Feature Request] Allow private groups to configure a delay for spectators

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#236]
Right now allowing people to live spectate a game allows them to cheat by sharing powerup timers with their teammates. A potential way to combat this would be to delay the feed to spectators by at least 1 minute.

**Comment by NewCompte** [comment]
That would actually be really easy to do.
If you can find other people interested in it, I can do it and convince lucky of its usefulness.

**Comment by Nick-Riggs** [comment]
@NewCompte up to you if you want to work on in it for classic. I'm going to mark it for Next consideration and close it for now. If you decide to work on it, reopen and mark it as such.
