### ISSUE TITLE
[Bug] When you join a group, it often times shows your previous account or name when it says "{player} has joined the group"

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#237]

**Comment by RonSpawnson** [comment]
Pretty easy to reproduce. Just login as one account, join a group. Leave the group. Log out, log into another account, and join the group.

**Comment by I-mess-up** [comment]
I've also experienced this bug.

**Comment by NewCompte** [comment]
Yeah, it's obvious from the code that this would happen.
