### ISSUE TITLE
[Bug] Chrome App conflicts with Tampermonkey

### ISSUE THREAD

**Issue by chrahunt** [tagpro-game/tagpro-issues#240]
Having the [TagPro Chrome App](https://chrome.google.com/webstore/detail/tagpro-capture-the-flag/bommelfnddjcbmbcfhmhjikpfphlebjh) installed prevents TamperMonkey from recognizing and applying userscripts to any TagPro domain related to the App.

![image](https://cloud.githubusercontent.com/assets/2312275/8140901/1afec67c-112e-11e5-860e-f39d02f8faa0.png)

To see that a domain is related, view the Google Chrome task manager and observe "App: " prepended to the name of the tab.

![image](https://cloud.githubusercontent.com/assets/2312275/8140883/f0832b9a-112d-11e5-9b79-eeb583ff23f7.png)

Removing the TagPro Chrome App from Chrome allows Tampermonkey to recognize the domain and associating the correct userscripts. This applies to Chrome 45.0.2427.7 dev-m (64-bit).

This is more for any others having a similar issue, since I don't know that this issue necessarily falls to you to fix. Any idea what could be causing this or who the right people to inform would be?

**Comment by I-mess-up** [comment]
I have the TagPro app and no problems with userscripts.

**Comment by Nick-Riggs** [comment]
Same, I have the app and have no issues.
