### ISSUE TITLE
[Bug] It said in chat that a player switched sides at the end of a game but neither the player's color in all chat nor the ball's color in the game changed to reflect that.

### ISSUE THREAD

**Issue by I-mess-up** [tagpro-game/tagpro-issues#243]
![screen shot 2015-06-19 at 10 29 10 pm](https://cloud.githubusercontent.com/assets/10187488/8265688/cfab6bd0-16d2-11e5-9f34-4fe9f6b37149.png)

**Comment by I-mess-up** [comment]
If it matters, that would have been my second switch. And [here](http://tagpro.eu/?match=26913)'s a link to the game overview on tagpro.eu.

**Comment by NewCompte** [comment]
Code to fix this is ready.
