### ISSUE TITLE
Private group sending people to pubs

### ISSUE THREAD

**Issue by raven-pride** [tagpro-game/tagpro-issues#245]
Hey, I think I figured out the oft-mentioned bug that sends people who are in private groups into pubs. I think it happens when a player tries to join a private game (via Red, Blue, or Spec) and the game has ended but everybody hasn't yet been kicked back to the group page.

**Comment by Nick-Riggs** [comment]
Need to see if we can duplicate the behavior.

**Comment by flymolotagpro** [comment]
It's due to the Rolling 300 userscript.

**Comment by cbtexan04** [comment]
I've personally seen this before, and I don't have that userscript. This behaviour has happened less and less though, and I haven't seen it in months. It very well maybe have been fixed inadvertently (OP posted ~8 months ago).

**Comment by Nick-Riggs** [comment]
This has been fixed.
