### ISSUE TITLE
[Suggestion] Re-shake the Map Ratings Occasionally

### ISSUE THREAD

**Issue by Blazeth** [tagpro-game/tagpro-issues#247]
I think the map ratings should be shaken occasionally (at http://tagpro-radius.koalabeast.com/maps), so the opinions are more accurate. This will also help the MTC process.

Every 3 weeks or so make all the ratings reset, and have each map rating button shake again.

If you have any free time in the process of making Next, it would be cool to update this in classic. If not, I think having it in Next is crucial.

**Comment by nrabins** [comment]
I'd personally like it to be tailored to the user and the map, so you'd get prompted to rerate played X map after Y times of playing it. Then you wouldn't have the issue of bugging players who don't play as frequently EVERY time they play the map.

**Comment by Nick-Riggs** [comment]
This has been added. It shakes the box every 10 plays of a map now.
