### ISSUE TITLE
Bring back more lenient team switching

### ISSUE THREAD

**Issue by nrabins** [tagpro-game/tagpro-issues#248]
Bring back switching to a losing team, even if it gives them a player advantage (at the expense of a save opportunity).

Rationale and convo with Lucky: http://i.imgur.com/dS8n84K.png

**Comment by NewCompte** [comment]
Done.

You don't keep a save when you switch.

**Comment by ButtonBill** [comment]
YISSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
