### ISSUE TITLE
Update TagPro to show both stickies, and/or educate /r/tagpro mods as to how they can choose which sticky is shown (if possible)

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#249]
TagPro has an awesome feature where the stickied post is displayed in game. This has been super helpful sharing announcements and timely event information (like competitive streams) with the general TagPro playing audience.

Reddit now allows two stickied posts. The game is still only showing one of those two. The moderators aren't even sure which stickied post gets displayed as shown by this comment: https://www.reddit.com/r/TagPro/comments/3fv9q7/me_complaining_publicly_about_a_couple_rtagpro/ctsorlx?context=1

We had a situation this Sunday where the "New Mods" stickied thread was the one shown in the game, and the "MLTP Streams" stickied thread wasn't shown.

I'd like to propose we either enhance TagPro to show both stickies, or educate the mods as to how they can choose which sticky is meant for in game (if this is possible).

**Comment by Nick-Riggs** [comment]
This is in production.
