### ISSUE TITLE
score zone padding? 

### ISSUE THREAD

**Issue by aschapm** [tagpro-game/tagpro-issues#256]
this looks like a pretty generous padding on the score zone for this map. is this by design or a bug? (the final point was made while the red ball was that far from the zone.)

<img width="1042" alt="screen shot 2015-09-06 at 2 09 27 pm" src="https://cloud.githubusercontent.com/assets/7052018/9721227/041bd528-5565-11e5-9186-c3f1d53c7b15.png">

**Comment by Nick-Riggs** [comment]
The server is sometimes out of sync with the client. On the server, the player touched the zone and it just so happens the client didn't update the player's position before ending and freezing the game play.
