### ISSUE TITLE
Tampermonky multiplies number of scripts every time a game loads

### ISSUE THREAD

**Issue by claytonnewberry** [tagpro-game/tagpro-issues#258]
I have test that it does it only on the main servers. Tampermonkey works fine on both Maptest and Tangent but not the main servers. Assuming the code is about the same for all of the servers I am just wondering if you guys can figure out why this is/tell me if it is on your side or Tampermonkeys side.

**Comment by Nick-Riggs** [comment]
Sorry, this is outside the scope of what we can help with.
