### ISSUE TITLE
Game switches

### ISSUE THREAD

**Issue by AMorporkian** [tagpro-game/tagpro-issues#26]
A switch that acts as though a player is sitting on that button the entire time when it's activated. When an enemy rolls over it, it switches control to the other team.

**Comment by rschamp** [comment]
I agree — the sprite for this should look like a lever or toggle rather than a momentary push button. This feature could open up some great new possibilities for map makers without drastically changing anything.

**Comment by Nick-Riggs** [comment]
I really like this idea for Next.
