### ISSUE TITLE
lots of packet loss, getting disconnected from radius for "network issues"

### ISSUE THREAD

**Issue by aschapm** [tagpro-game/tagpro-issues#261]
i used to get pings in the 20-40 range, but lately it's been 40+ with some amount of packet loss, then i get booted from the game for network issues. so far i watched the video and ran the mtr on my normal server, radius (attached screeenshots). i also tried explaining the issue to my isp which they couldn't figure out but had me power cycle the modem (and they sent a boosted signal to clear the pipes or something). i think (but can't quite remember if) this started on wednesday 9/30, when i upgraded to el capitan. what could be going wrong? 

<img width="486" alt="screen shot 2015-10-03 at 8 49 55 pm" src="https://cloud.githubusercontent.com/assets/7052018/10265894/87a42e1c-6a10-11e5-9b43-5ff79fac88db.png">
<img width="489" alt="screen shot 2015-10-03 at 6 25 51 pm" src="https://cloud.githubusercontent.com/assets/7052018/10265895/87a47a70-6a10-11e5-99fa-8651602fdc1b.png">

**Comment by Nick-Riggs** [comment]
Hi, so you have a ton of loss on the very first node in your route. See how it says 4.3% loss at 192.168.8.1? That means you are losing that much data right off the bat, that's really bad. That is likely your router and/or cable modem. Try restarting it. If you are wireless, you could try going wired but that is a ton of loss to simply be a wireless issues. If the problem persists, you will need to get your ISP involved.
