### ISSUE TITLE
Name spontaneously changes

### ISSUE THREAD

**Issue by Bamaman11** [tagpro-game/tagpro-issues#264]
Multiple times on Pi, I have been playing as my reserved name BamaBall.  A game will finish, and when entering the next game, my displayed name has changed to NAME HERE.  I am playing on a Mac with OS X 10.9.5, Chrome 46.0.2490.80, with Tampermonkey running a few various scripts (none that would involve changing my name.  Any ideas?

**Comment by Nick-Riggs** [comment]
Almost certainly a script. The string "NAME HERE" doesn't even appear in the TagPro code base.
