### ISSUE TITLE
[Suggestion] Enhance respawn camera (particularly to eliminate "blind spawns")

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#267]
I found this on the subreddit and I think that it would be a great thing for the dev team to consider (if not for classic, at least Next). 

Some have pointed out advantages to keeping the camera functionality as is (seeing where enemy FC goes if your flag is out) and some have pointed out disadvantages to current camera functionality ("blind spawns" causing users to spike themselves if they spawn right next to one).

My proposal would be to allow the user to press a button to toggle between seeing either the camera near their death or the camera near their spawn. It would be up to the user to determine which information is more valuable to them at the time (or swap back and forth and see both).

Many games offer a more advanced spectate system like this (counterstrike comes to mind) and I think this could solve the "blind spawn" issue.

Edit: Here's another proposal someone had- Smoothly move camera from death spot to spawn spot. A user has already whipped together a userscript to do this take a peak: https://www.reddit.com/r/TagPro/comments/3t0vzh/suggestion_respawn_camera/cx2nt5k

I almost like this better than my suggestion because it's simple and requires no user input.

Please see additional details here:https://www.reddit.com/r/TagPro/comments/3t0vzh/suggestion_respawn_camera/

By the way, does the dev team even read these any more? I've created tons of issues that have jaf no response. Do you not care about feedback anymore or do you have a more preferred way of intaking this?

**Comment by Nick-Riggs** [comment]
Let's consider this for next. I actually plan on reaching out to you and other streamers for input on what should be including in TagPro Next streaming to make your experience better.
