### ISSUE TITLE
TagPro is has been broken on firefox 42 on GNU/Linux for a week now

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#268]
See reddit comment. https://www.reddit.com/r/TagPro/comments/3tv40i/dear_devs_tagpro_has_been_broken_on_firefox_42_on/

Unfortunately any sort of response has been nonexistent on here lately so people are trying to hound you on Reddit instead. I'm adding this as a best faith hoping that one day the devs return to being responsive on github.

**Comment by Nick-Riggs** [comment]
We are troubleshoot the issue in that thread.
