### ISSUE TITLE
Tiles FC can't pass through

### ISSUE THREAD

**Issue by AMorporkian** [tagpro-game/tagpro-issues#27]
Everyone except flag carriers can move through this tile.

**Comment by nrabins** [comment]
I love this idea. In my mind it's a wall that is only tangible to FCs. This makes it a little more strategic than just a murder wall, as FCs can use them to juke. I think it gives it a bit of balance that way.

**Comment by jufda** [comment]
Interesting idea, but how could a 40x40 tile intuitively explain itself as "only FC cannot move through"? Would this just add complexity to the game, making it harder to approach and learn?

**Comment by nrabins** [comment]
My thought was that it would be a "ghost wall" tile that would solidify
once you grabbed the flag. I think that with this clue, it would be fairly
obvious once a player grabbed the flag.

**Comment by Nick-Riggs** [comment]
Very likely this will be in Next.
