### ISSUE TITLE
[Bug] Unavoidable AFK kick

### ISSUE THREAD

**Issue by JohnnySZS** [tagpro-game/tagpro-issues#270]
My Chrome crash randomly while playing a neutral flag map when I had the flag, so I refreshed and got put into the same game, but I had to wait 20 seconds. Before I could even spawn, I was kicked for being AFK, despite me not even having a chance to move. I pressed back and got put into the same game, and had to wait 20 seconds. This time, while waiting my 20 seconds to respawn, I pressed all my arrow keys and tried chatting but I couldn't. I got kicked again for AFK again, despite pressing buttons. I pressed back again, and got put into the same game. This time, however, I could chat before I respawned and I was able to spawn in.

So the problems would be either,
1. There is a bug where the game doesn't register any of your keypresses when you re-enter a game
or 
2. The AFK kick timer is unavoidable at times.

Thanks!

**Comment by Nick-Riggs** [comment]
Something else was kicking you - not sure what tho. People refresh and have that wait all the time and have no issues getting kicked for AFK.
