### ISSUE TITLE
High ping with new radius (from Boston). Segment also climbed drastically recently.

### ISSUE THREAD

**Issue by banzaiTP** [tagpro-game/tagpro-issues#271]
I'm not complaining or asking for you to fix my personal ping lol, just didn't want to clutter up the sub and figured I'd put it on the record in case other people are having the same sorts of connectivity problems. E told me sometimes these things resolve themselves, but I figured if I was getting routed to some "bad node" or something and others also experienced it, maybe that's something that can be addressed? (In case it's not obvious, I don't know anything about this stuff.)

Anyway, this is what now constitutes good ping for me since the switch. I used pingplotter. (And I know I'm supposed to let it run for a while. I've run them for 15 minutes and this is fairly typical.)

Hop  Sent  PL%    Min     Max    Avg  Host Name / [IP]
  1         24    0       0.38    0.58   0.50  wireless_broadband_router.home 
  2         24    0       5.77   26.03   8.33  lo0-100.bstnma-vfttp-337.verizon-gni.net [173.76.59.1]
  3         24    0       7.51   23.78  10.85  t0-12-0-6.bstnma-lcr-21.verizon-gni.net [100.41.0.126]
  4         0  NaN      0       0      0   --------------  [-]
  5         0  NaN      0       0      0   --------------  [-]
  6         24    0       12.96   18.88  15.65  0.ae6.br1.nyc1.alter.net [140.222.228.131]
  7         24    0       13.18   24.55  15.56  ip4.gtt.net [173.205.47.145]
  8         24    0       25.83   36.53  28.07  xe-10-3-3.nyc41.ip4.gtt.net [89.149.180.166]
  9         24    0       83.48   98.56  85.41  as20473.ae2.ar2.ewr1.us.as4436.gtt.net [69.31.34.210]
 10        24    0       83.49   92.12  85.51  108-61-248-5.constant.com [108.61.248.5]
 11        24    0       83.19  351.45  96.27   --------------  [108.61.244.10]
 12        24    0       83.27   86.03  84.61  tagpro-radius.koalabeast.com [104.243.35.146]

My ping used to be probably 20-30. I don't even mind ~100, but it's routinely more like 170. I never have loss, I just start having things skyrocket around the 8th-9th hop.

For whatever reason, Segment went way up as well:

Hop  Sent  PL%    Min     Max    Avg  Host Name / [IP]
  1    24    0           0.46    0.66   0.54  wireless_broadband_router.home 
  2    24    0           6.40    8.48   7.30  lo0-100.bstnma-vfttp-337.verizon-gni.net [173.76.59.1]
  3    24    0           7.31   19.00  10.94  t0-12-0-6.bstnma-lcr-22.verizon-gni.net [100.41.0.128]
  4     0  NaN      0       0      0   --------------  [-]
  5     0  NaN      0       0      0   --------------  [-]
  6    24    0          13.70   48.12  19.78  0.ae5.br1.nyc1.alter.net [140.222.228.107]
  7    24    0          13.84   21.06  16.48  ip4.gtt.net [173.205.47.145]
  8    24    0          83.46  109.57  85.93  xe-10-3-3.nyc41.ip4.gtt.net [89.149.180.166]
  9    24    0          82.77   90.89  84.96  as20473.ae3.ar2.ewr1.us.as4436.gtt.net [69.31.95.6]
 10    24    0         93.92  107.88  96.06   --------------  [108.61.244.225]
 11    24    0         83.35   87.89  85.01   --------------  [108.61.244.74]
 12    24    0         83.23   86.65  84.76  208.167.241.16.vultr.com [208.167.241.16]
 13    24    0         83.58   89.66  85.18  tagpro-segment.koalabeast.com [104.238.133.186]

Anyway, like I said, just figured I'd put something on the record in the event other people have similar issues and you need stats to compare.

And for the record, other ping: Pi-40, Origin-40, Sphere-60, Centra-75. (Oddly, with the exception of Pi remaining constant, those all seem to have greatly improved.)

Edit: NVM for the other servers, played Pi and Centra and ping was hopping all over the place :-(

Thanks.

**Comment by Nick-Riggs** [comment]
See how the ping jumps from 15ish to 85ish right in the middle? That's happening in the gtt.net network. The bad news is that's neither your ISP's network or the host's network. It's just a bandwidth provider. So really, there isn't much we or the host can do about. It's likely most of your routes to the servers are passing through it if you are experiencing the same thing on other servers. The good news is that bandwidth providers usually fix this stuff pretty quick, so hopefully you don't have to deal with it long.

**Comment by banzaiTP** [comment]
Great, thanks. Didn't necessarily expect anything could be done on your end, but figured in the event that it could it might be useful to have plenty of info on your end. Thanks again.
