### ISSUE TITLE
[BUG] Long Sound Effect Delay

### ISSUE THREAD

**Issue by MrComrade** [tagpro-game/tagpro-issues#276]
When I start up every/any game of TagPro, there is no music or sound effects for about 10-20 seconds.  Then suddenly ill hear the countdown, "GO!", and all the sound effects so far, all at once.  Then it works for a bit, then it happens again. 

So basically I have a big sound delay problem, and have not found any threads that are quite like mine yet.  I know it has to do with my laptop though, because my desktop runs it fine.

Thanks

**Comment by Nick-Riggs** [comment]
What kind of computer is it and how old is it? What operating system are you using? Also - what browser are you using and does this happen in any browser you use?

**Comment by MrComrade** [comment]
I think the laptop is around 4-5 years old.
It is a HP Pavillion g6 Notebook with Windows 10.
It happens in every browser I use.

It is a pretty crappy laptop, but figure TagPro is easy to run.

**Comment by Nick-Riggs** [comment]
That's strange stuff. My guess is that it's a driver issue. Can you ensure you have the latest sound drivers installed for your laptop for Windows 10?

**Comment by MrComrade** [comment]
Not sure why I didn't think of that but I definitely can check.

**Comment by MrComrade** [comment]
My sound driver did need updated, and from what I can tell it helped.  Music and sound effects do not lag anymore in game, which was the main issue.  However, the music and sound effects (Countdown and "GO!") are still delayed at the start.  I can deal with that if there is no other solution.

**Comment by MrComrade** [comment]
May still be some delay in game sound effects, but not as noticeable.

**Comment by Nick-Riggs** [comment]
In a game that is having issues, can you check to see if you have any JS errors? CTRL+SHIFT+J will bring up the JS console, just copy/paste anything you see into here.

**Comment by MrComrade** [comment]
**I am running Cam's Pixel Perfect texture pack, which I am assuming is causing all the particle texture errors.**

**Under JS**
PixiParticles: using particle textures from different images may hinder performance in WebGL global-game.js:1:377755
The redrawBackground function has been deprecated. global-game.js:1:124235

TagPro version 3.2.1 global-game.js:1:915
Powered by PixiJS. Currently running in WebGL mode global-game.js:1:1022
Developers: LuckySpammer, steppin, NewCompte, AnkhMorpork, Ly, ylambda

**Under CS**
PixiParticles: using particle textures from different images may hinder performance in WebGL global-game.js:1:377755
Expected color but found 'notallowednotallowedtagpro-radius'.  Error in parsing value for 'background'.  Declaration dropped. webconsole.xul
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. style.css:591:11
Unknown property '-moz-border-radius'.  Declaration dropped. style.css:790:25
Unknown property '-moz-box-shadow'.  Declaration dropped. style.css:793:22
Unknown property '-moz-border-radius-topright'.  Declaration dropped. style.css:808:35
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. style.css:811:38
Unknown property '-moz-border-radius-topleft'.  Declaration dropped. style.css:814:35
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. style.css:817:38
Error in parsing value for 'background-image'.  Declaration dropped. style.css:821:6
Unknown property '-moz-box-shadow'.  Declaration dropped. style.css:837:22
Error in parsing value for 'background-image'.  Declaration dropped. style.css:853:7
Unknown property '-moz-background-size'.  Declaration dropped. style.css:872:27
Unknown property '-moz-border-radius-topright'.  Declaration dropped. style.css:875:35
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. style.css:878:38
Unknown property '-moz-border-radius-topleft'.  Declaration dropped. style.css:881:34
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. style.css:884:37
Error in parsing value for 'background-image'.  Declaration dropped. style.css:990:22
Error in parsing value for 'background-image'.  Declaration dropped. style.css:991:22
Error in parsing value for 'background-image'.  Declaration dropped. style.css:1009:22
Error in parsing value for 'background-image'.  Declaration dropped. style.css:1010:22
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. style.css:591:11
Unknown property '-moz-border-radius'.  Declaration dropped. style.css:790:25
Unknown property '-moz-box-shadow'.  Declaration dropped. style.css:793:22
Unknown property '-moz-border-radius-topright'.  Declaration dropped. style.css:808:35
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. style.css:811:38
Unknown property '-moz-border-radius-topleft'.  Declaration dropped. style.css:814:35
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. style.css:817:38
Error in parsing value for 'background-image'.  Declaration dropped. style.css:821:6
Unknown property '-moz-box-shadow'.  Declaration dropped. style.css:837:22
Error in parsing value for 'background-image'.  Declaration dropped. style.css:853:7
Unknown property '-moz-background-size'.  Declaration dropped. style.css:872:27
Unknown property '-moz-border-radius-topright'.  Declaration dropped. style.css:875:35
Unknown property '-moz-border-radius-bottomright'.  Declaration dropped. style.css:878:38
Unknown property '-moz-border-radius-topleft'.  Declaration dropped. style.css:881:34
Unknown property '-moz-border-radius-bottomleft'.  Declaration dropped. style.css:884:37
Error in parsing value for 'background-image'.  Declaration dropped. style.css:990:22
Error in parsing value for 'background-image'.  Declaration dropped. style.css:991:22
Error in parsing value for 'background-image'.  Declaration dropped. style.css:1009:22
Error in parsing value for 'background-image'.  Declaration dropped. style.css:1010:22
The redrawBackground function has been deprecated. global-game.js:1:124235

TagPro version 3.2.1 global-game.js:1:915
Powered by PixiJS. Currently running in WebGL mode global-game.js:1:1022
Developers: LuckySpammer, steppin, NewCompte, AnkhMorpork, Ly, ylambda

**Comment by MrComrade** [comment]
Ill run it on any other games that I"m having issues in and check again

**Comment by Nick-Riggs** [comment]
Sorry, I'm out of ideas. I'm going to close this for now but update if you have any breakthroughs.
