### ISSUE TITLE
Popup Adware

### ISSUE THREAD

**Issue by rwalt92** [tagpro-game/tagpro-issues#279]
When I join a new game, my arrow and WASD keys do not move my ball. When I hit enter, a new tab automatically opens to this page: https://stock.adobe.com/search?k=

Any way to resolve this?

**Comment by I-mess-up** [comment]
Check chrome://extensions for unrecognized extensions (or the equivalent if you do not use chrome). Sounds like an issue specific to you.

**Comment by rwalt92** [comment]
I don't seem to have any extensions that are out of the ordinary.

**Comment by dgarndt** [comment]
This has also been happening to me. My arrow keys don't work and enter opens that same webpage on a new tab, I've gotten kicked out for being AFK about 5 times...

No unrecognized extensions

**Comment by I-mess-up** [comment]
I can’t reproduce this with all my extensions and scripts or without. Each of you should try it and see if this issue happens with no extensions or scripts whatsoever (including general web extensions like an ad blocker). Perhaps there is a rogue ad that is hijacking the keys, and playing with no extensions could reveal this. If you can’t reproduce the issue with no extensions, then it means that one of your extensions is at fault, and you should try enabling them all one by one until you find the problem. You could also try running Malwarebytes.

For reference:
- What OS are you each running?
- What browser?
- Does the issue happen in every single game or just some?

**Comment by dgarndt** [comment]
Ok I disabled all my extensions and it still happens. I don't know how to remove scripts. I don't have any ad blockers. 

I am on OS X El Capitan. Using Chrome. I also tried Safari and it was still doing it. It happens most games.

**Comment by I-mess-up** [comment]
Interesting. It sounds like there may be some sort of infected advertisement, though it’s possible you have a virus. Can you try downloading Malwarebytes from [here](https://www.malwarebytes.org/dl-confirm/ <https://www.malwarebytes.org/dl-confirm/>) (just click “Download Free Version” in the lower left), run it, and let us know the results?

I think it has happened before that certain ads have somehow disrupted TagPro function, so I want to eliminate the possibility of a virus on your end.

**Comment by dgarndt** [comment]
When I try to download Malwarebytes it says, "You can’t open the application “mbam-setup-2.2.0.1024.exe” because Microsoft Windows applications are not supported on OS X." Is there a version for Macs?

**Comment by I-mess-up** [comment]
Yeah, there’s a version for Mac (that I’ve downloaded before) so I figured that would give you the Mac version. My mistake. 

[The Mac version can be found here](https://www.malwarebytes.org/antimalware/mac/ <https://www.malwarebytes.org/antimalware/mac/>).

**Comment by I-mess-up** [comment]
Yeah, there’s a version for Mac (that I’ve downloaded before) so I figured that would give you the Mac version. My mistake.

[The Mac version can be found here](https://www.malwarebytes.org/antimalware/mac/)

**Comment by dgarndt** [comment]
Ok, did the scan. Found no malware or adware

**Comment by I-mess-up** [comment]
Sounds like an issue with a specific ad, then. I’m sure a developer will look into it when they can.

**Comment by dgarndt** [comment]
Ok well thank you so much for your help.

**Comment by I-mess-up** [comment]
[I found this on the same topic](https://www.reddit.com/r/TagPro/comments/46vhxe/ad_spam_in_tagpro/).

**Comment by Nick-Riggs** [comment]
This doesn't strike me as adware - because opens a link to adobe's website, not a malicious site. This is more likely a bug with the adobe flash plugin for the browser.
