### ISSUE TITLE
It's possible to spectate and play in a private game at the same time

### ISSUE THREAD

**Issue by RuudVerbeek** [tagpro-game/tagpro-issues#280]
This allows cheating in competitive games, can something be done about it? Dragging yourself out of the team into spectators and launching in a different tab allows you to have a full viewport in-game which gives a huge advantage.

**Comment by Nick-Riggs** [comment]
My initial reaction is that the leagues manage this pretty well through rules. I doubt this is a common problem. I could be swayed tho.

**Comment by RuudVerbeek** [comment]
Thanks for the response. I was elected for commissioner in ELTP S7 and just happened to catch people discussing this tactic on mumble last night. "Cheating", under which this would fall, is already prohibited according to the rules, but it would still be very difficult to detect people doing it and I wouldn't even be surprised if some people have already used it in competitive play in the past. It gives a huge advantage to know where other players are, always see powerup pickups and generally know what's going on everywhere on the map.

I can think of one rule that would somewhat fix the issue, but it not completely and it would not be convenient. This would be requiring self assignment to be disabled in a league game. It would still be possible to perform the cheat if it was organized with the group leader (e.g. a team member or captain, who would help the players by dragging them out) and it would make substitutions difficult to manage.

I guess this issue is just like the entire userscript whitelist fuss, as we cannot really detect abuse of it and just would have to make our own rules against it and hope our players obey. However, TagPro already has a good built-in protection against zooming out (only sending what is inside the player's viewport), so I'd like to see a fix for this workaround as well.

**Comment by Nick-Riggs** [comment]
Someone could just use two different accounts - or not even log in for the spectator account. So detecting by account isn't helpful. We'd have to detect by IP address to be effective at all. But even then, a crafty person would just used a second laptop on a VPN to bypass it. 

Thoughts @NewCompte?

**Comment by RonSpawnson** [comment]
I think delaying spectator feed by 20 seconds or so is another potential option.

**Comment by RuudVerbeek** [comment]
I can see a couple of issues with that:

* Powerup times are still visible, and possibly even easier to read 20 seconds later

* Spectators and streamers want to listen live to the players on Mumble

* Group leader might be spectating and wouldn't be able to take the right actions in time (like timeouts). Same goes for instant substitutes.

**Comment by Nick-Riggs** [comment]
Now I think of it, this is already solved. League rules should require group leaders to turn off "self assignment" once teams and spectators are step up correctly and about to enter the game. That will make it impossible for anyone to sneak into the group and put themselves in the spectators slot.

**Comment by RonSpawnson** [comment]
Couldn't a player still smurf as an alt account and get into specs before the game started? Even if self assign is off, they could smurf their way in prior to the game starting

**Comment by Nick-Riggs** [comment]
It's up to the leader of the group to know that all the players are the correct players for the match and that the players in the spectator slot are streamers. If they think otherwise, kick or move the player to the unassigned box.

**Comment by NewCompte** [comment]
I have made something that fixes this, but the workaround that Lucky mentioned would work anyway..

**Comment by RuudVerbeek** [comment]
Thanks NewCompte. I'm not in favour of implementing an auto-assignment rule, but this already eliminates most of the ways. I'll still check with my fellow commissioners what they think about a rule.
