### ISSUE TITLE
[suggestion] clickable hyperlink in chat with site restriction

### ISSUE THREAD

**Issue by nov4chip** [tagpro-game/tagpro-issues#282]
Hello,
I was thinking of faster ways to get new players to understand the game better. It would be helpful to have clickable links in chat in order to get them fast to tagpro homepage, reddit strategy guides, youtube videos (some of the newcomers are just too lazy to do on their own). I do acknowledge that this could create serious spam issues, so maybe just tagpro domains, reddit (limiting to r/tagpro, r/ELTP etc.) and maybe youtube should have clickable links, other domains can remain plain text.
Maybe this is just stupid, anyways thanks for your time!
EDIT: I also understand that having a player leave the site is not good money-side, due to ads being displayed at the end of the match. Maybe you can make it open in another tab and let the tagpro window stay in foreground?

**Comment by ylambda** [comment]
Thanks for the suggestion!

To help orient new players we plan to have a tutorial in the new tagpro we're working on.

I'd want to avoid putting links into the game. It complicates things a lot.
