### ISSUE TITLE
Bug: Server home page instructions overlapping each other

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#286]
Platform: Mac.
Browser: Observed in Chrome and Safari

Here is what it looks like: http://i.imgur.com/rEZAVRy.png

**Comment by NewCompte** [comment]
I can't get this to happen on Chrome (Windows) even if I resize the window.

**Comment by RonSpawnson** [comment]
Do you have a mac? Myself and another person on mumble who had a macbook both experience this.

I also tried resizing my window and changing the zoom level but it always shows up this way.

**Comment by RonSpawnson** [comment]
I've tested and noticed this happens regardless of my browser. I notice it on Chrome, Safari, and Firefox on my Retina Macbook Pro with OS X El Capitan.

**Comment by I-mess-up** [comment]
Same here. Zooming out to even 50% does nothing to fix the issue. (Also retina MBP, all 3 browsers).

**Comment by NewCompte** [comment]
It has been fixed I think.

**Comment by RonSpawnson** [comment]
Confirmed fixed - thanks!
