### ISSUE TITLE
If chat is opened while a movement key is pressed, movement will continue in that direction

### ISSUE THREAD

**Issue by TPSnack** [tagpro-game/tagpro-issues#39]

**Comment by RonSpawnson** [comment]
Any updates? I strongly contend this should be fixed, but at the very least Holcomb is right. If this is intended to be a feature it is flawed. The second I close chat and start playing, of the second the window regains focus, if I am not holding a directional key my ball should not move.

This is a bug that's being masqueraded as a feature.

Any chance this could be configurable and be off by default?

**Comment by RonSpawnson** [comment]
Any updates on this issue? There are still new players running into this issue:

https://www.reddit.com/r/TagPro/comments/4096fz/why_does_typing_while_playing_cause_my_ball_to/

**Comment by RonSpawnson** [comment]
Any progress on this?

**Comment by RonSpawnson** [comment]
Bump, as per https://www.reddit.com/r/TagPro/comments/5gjado/i_am_logos_i_dont_know_what_happened/

**Comment by RonSpawnson** [comment]
Ping, as per https://www.reddit.com/r/TagPro/comments/eh8w66/a_polite_request_to_fix_the_glitch_where_you_get/

**Comment by RonSpawnson** [comment]
More new players running into this issue https://www.reddit.com/r/TagPro/comments/gl1g45/keys_sticking

**Comment by RonSpawnson** [comment]
A momentous occasion! This has finally been fixed!

https://www.reddit.com/r/TagPro/comments/n0sm2t/tagpro_future_group_community_update_6_april_28th/

**Comment by Nick-Riggs** [comment]
Ron's 7-year crusade has come to an end.
