### ISSUE TITLE
Allow moderators to issue official warnings

### ISSUE THREAD

**Issue by tim-sanchez** [tagpro-game/tagpro-issues#51]

**Comment by steppin** [comment]
the one thing official warnings can provide that broadcasted moderator chat doesn't is a history of warnings alongside actual reports.  It would be kind of like official warnings that cops can give; other cops are aware of them when they pull you over next time

**Comment by tim-sanchez** [comment]
Could mod chat not be the same?

**Comment by Nick-Riggs** [comment]
https://github.com/tagpro-game/tagpro-issues/issues/246
