### ISSUE TITLE
Having scoreboard open while timing out for AFK does not kick player to homepage

### ISSUE THREAD

**Issue by theVDude** [tagpro-game/tagpro-issues#55]
Expected Behavior: IDK, I don't actually get kicked for AFK but I guess kicked to homepage?

Steps to reproduce: Join game, hit ESC to bring up scoreboard, don't hit anything else

You can see players joining on the scoreboard, it's kinda weird.

**Comment by steppin** [comment]
I cannot seem to reproduce this on the new pixi client.  Can you check at http://tangent.jukejuice.com and close this if you cannot reproduce it there?

**Comment by theVDude** [comment]
Seems to be fine now!
