### ISSUE TITLE
TagPro School Flair

### ISSUE THREAD

**Issue by Freshrr** [tagpro-game/tagpro-issues#60]
So basically this flair works as an incentive for newer players to learn the mechanics of the game.
How it would work:
The player looks over a quick study guide (probably an info-graphic) of what basic things are in-game. The study guide would go over power-ups, spikes, walls, and all other fundamental elements in TagPro. And of course the study guide should look appealing so that it's very easy to learn. After they look over the study guide, they take a quick 5-10 question quiz about what they went over. If they score 8/10 or better they get a nice graduates cap flair to show they are proficient in TagPrology.

**Comment by ylambda** [comment]
I'm not in favor of this because quizzes are lame.

**Comment by AMorporkian** [comment]
I'm in favor of this because ylambda is lame.

**Comment by steppin** [comment]
would it be tagproology?
