### ISSUE TITLE
Add a higher level donor flair

### ISSUE THREAD

**Issue by cbtexan04** [tagpro-game/tagpro-issues#62]
As suggested on the TP subreddit, it would be advantageous to have a donor flair higher than we have now. This wouldn't cost the devs much in time at all, and would bring in additional income. Many diamonds have stopped donating once they met the highest flair level because, well, there's no gain for donating past that (as selfish as that sounds).

**Comment by AMorporkian** [comment]
We aren't opposed to this at all and are brainstorming what could beat a diamond. If anyone has any suggestions, make them known!

**Comment by cbtexan04** [comment]
It might be advantageous to make it into a contest; in fact, I'll go and get started on posting one: http://www.reddit.com/r/TagPro/comments/2r7nvl/contestreward_if_there_were_a_donor_flair_above/

**Comment by cbtexan04** [comment]
Some of the feedback I've received thus far, along with some of my own suggestions:

-Yacht
-Gold diamond
-The amount in 'bling' text (or on coin)
-A golden outline around your ball
-The monopoly guy
-Money bags

I find the outline pretty awesome for an idea-- it let's the player pick a flair of their choice (they don't have to decide between the $250 flair or their monthly flair), while still letting everyone else know of their contribution. Could even start with bronze for an outline, and have silver/gold for higher donation levels.

**Comment by steppin** [comment]
https://www.iconfinder.com/icons/353980/palm_palmboom_palmtree_icon#size=20

**Comment by I-mess-up** [comment]
There's been enough joking about the palm tree that I think it could legitimately be the flair, and a kind of inside joke.

**Comment by cbtexan04** [comment]
Eh, personally, I get the whole palm tree joke, but to have it by itself doesn't really strike me as something a higher level donor would want. Perhaps if it was a yacht next to a palm tree island, that would be more appropriate.

I'd really like to have the devs chime in on the whole bronze/silver/gold outline of the ball, and/or a bronze, silver, gold outline of the player's name. Those two are perhaps two of my favorite ideas that have been suggested.

**Comment by I-mess-up** [comment]
Now that you mention it I like the yacht and Palm tree island. It is actually desirable but includes the reference.

**Comment by steppin** [comment]
> I'd really like to have the devs chime in on the whole bronze/silver/gold outline of the ball, and/or a bronze, silver, gold outline of the player's name. Those two are perhaps two of my favorite ideas that have been suggested.

Personally, I think this would be confusing as new players would probably think it is some special ability (like tagpro).  I think some subtle drawing on the ball itself could work though as long as it's still easy to discern what team a ball is on

**Comment by cbtexan04** [comment]
Oh very true, I forgot about powerups (like tagpro) that would affect an outline of a donor. What about the name being outlined, in something like this? http://www.pimp-text.com/

**Comment by Nick-Riggs** [comment]
Top hat?

https://www.iconfinder.com/icons/324984/black_hat_hat_internet_marketing_optimization_seo_web_icon#size=128

**Comment by cbtexan04** [comment]
Finding some decent icons on that site. These two aren't too terrible:

https://www.iconfinder.com/icons/325010/buy_cash_coin_conversion_currency_dollar_financial_make_money_money_payment_price_sale_shop_store_webshop_icon#size=128
https://www.iconfinder.com/icons/324991/achievement_award_badge_best_conversion_gift_gold_medal_prize_reward_ribbon_trophy_win_winner_icon#size=128

From what I'm seeing, there's a ton of options. It's just which one fits best :)

**Comment by cbtexan04** [comment]
Whoops, I forgot to add this one too; kinda made me laugh:
https://www.iconfinder.com/icons/213724/business_buy_card_cash_checkout_credit_donate_financial_income_method_offer_online_order_payment_price_sale_service_shop_shopping_visa_icon#size=24

**Comment by Moosemaster21** [comment]
Pls devs close the issue <3

**Comment by cbtexan04** [comment]
Eh, idk, could push for a $500 flair ;)
