### ISSUE TITLE
Method to verify account ownership

### ISSUE THREAD

**Issue by TagPro-PreciousRoy** [tagpro-game/tagpro-issues#63]
It would be super helpful for [the Reddit flair bot](https://github.com/TagPro-PreciousRoy/tagpro-flair-bot-django), and other websites that wish to link a TagPro account with user accounts if there was some way for a 3rd party to verify that a person has control of a TagPro account.  The method that I propose is this:

 * In account settings, there is a new field "API key" that contains a unique key associated with the account.  For security it would be nice if this expires X hrs after it's generated.
 * The response for a single profile ``/profiles/<profile id>?key=<api key>`` should include a key ``verified: [true|false]`` if the key matches the profile.

This way only the person who has control of the account has access to the key, and you don't have to chance losing your reserved name to prove you own the account.

This might go in nicely with #11.

**Comment by AMorporkian** [comment]
This is a good idea.

**Comment by TagPro-PreciousRoy** [comment]
Bump. Not sure if this is still relevant with Next, but hope 3rd party auth can be worked in if not.
