### ISSUE TITLE
Opt out of certain play styles. ie, a no centerflag mode or vice versa. 

### ISSUE THREAD

**Issue by chelseafcTP** [tagpro-game/tagpro-issues#65]
I feel strongly against centerflags and have heard the same from a good amount of people and I probably know a lot of people who Love them (look at center flag leauge.) So I think it would be a great feature to be able to toggle game styles on or off.

For instance when I'm really looking to practice and get several CF maps in a row not only am I not enjoying the games my purpose to practice for league things gets ruined. CF has no application to my current reasons for playing tagpro and it drains the fun instantly when I know I'm going to have to play through the map. Especially with the new DC rules I'm forced to endure.  

I've found pubs have more CF maps than ever and I don't enjoy them. I feel that they're a separate game from the tagpro I started playing. Every increase in percentage of them my the MTC is less incentive for me to pub and to insulate myself in the mumble community. I think that's sad because part of this game is pubbing to learn from and teach other players and I just find I really have to motivate myself to do it where before CF this wasn't the case. I think it would make pubbing better for players on  both sides of this issue. Those who don't like CF can opt out and big fans can have pub sessions where they can play them over and over. 

Either that or put a strict low percentage of them allowed in game for the MTC. 

Thanks for considering. 
chelseaFc

**Comment by ManbearTagPro** [comment]
I really like this suggestion, and I think that to add onto it, it'd be fun to add in other game modes such as minigames (caravan, snipers, hockey, etc.) and OFM (a ranked OFM game mode would be really, really cool and lots of fun). There's a lot of room for expansion in terms of what it means to be playing TagPro and I think it would be healthy for the developers to look into expanding that idea to include fresh, creative gameplay.

**Comment by I-mess-up** [comment]
I will second the ranked OFMs

**Comment by AMorporkian** [comment]
Other suggestions should go into new issues. This issue is only about opting out. Please create another one if you want more gamemodes.

**Comment by ManbearTagPro** [comment]
Sorry! Will do.

**Comment by RonSpawnson** [comment]
+1

**Comment by Nick-Riggs** [comment]
Next will have this functionality - assuming we have the player base to support it.
