### ISSUE TITLE
Consistent chat messages 

### ISSUE THREAD

**Issue by NugaSausage** [tagpro-game/tagpro-issues#66]
As seen in this link (http://www.reddit.com/r/TagPro/comments/2r6hhi/inconsistency_in_messages/) and this link (http://i.imgur.com/lDxjFJs.jpg), some consistentcy in the messages would be nice for the user interface, to show professionalism and an attention to detail.

Not a big deal, but seems easy enough.

**Comment by I-mess-up** [comment]
This is the type of thing that Ankh likes to implement immediately. Wait and see…

**Comment by steppin** [comment]
fixed, will hit servers next time we push

**Comment by I-mess-up** [comment]
And by Ankh I meant steppin. Thanks!

**Comment by I-mess-up** [comment]
Close the issue?

**Comment by steppin** [comment]
we decided to leave issues open until the code hits production
