### ISSUE TITLE
New Game Modes

### ISSUE THREAD

**Issue by ManbearTagPro** [tagpro-game/tagpro-issues#67]
At the moment, TagPro only has capture the flag and neutral flag game modes. These are both exceedingly fun for me, but I feel they can grow stale for some, especially in public games. If TagPro were to implement new game modes, it would diversify gameplay in public games and create a sense of freshness that TagPro may be lacking. A few ideas I came up with off the top of my head was having a minigame gamemode (players could participate in games like Snipers, Hockey, and Caravan) and an Open Field Masters gamemode where players could play public OFM. A ranked OFM gamemode would be even cooler, I think. However, I have no idea how this idea would be practically implemented. Maybe the devs could adopt the method that lots of first person shooters like CoD and Halo use for multiplyer matchmaking by having multiple playlists for different game types that players could choose on the Tagpro.gg homepage.

**Comment by RonSpawnson** [comment]
This would be a big change, but could be really exciting. I suppose one problem would be getting enough users to support different game modes.

One option would be allowing the user to pick the normal "Play now" or a different "Play special mode" (name sucks, but you get the idea). This special mode could rotate, either every day or every hour, every week, whatever. Maybe it's zombie mode, maybe it's ofm's, maybe it's hockey, maybe unfortunate sniper, maybe something new? But each player could choose to play standard pubs or whatever the current special game mode is.
