### ISSUE TITLE
Ghost ball return after portal entry death

### ISSUE THREAD

**Issue by ScottAbbey** [tagpro-game/tagpro-issues#84]
Caught some footage during a US Contenders match where a ball who was popped was later credited with a return.

The clip is [here](https://www.youtube.com/watch?v=kbaxZvpt0zo), showing the entirety of the blue ball's carry.

At the same time as Thiradell pops Nqoba, the portal near them is triggered.  When Thiradell crosses the exit portal, he is popped.

I counted Nqoba's returns for the game by watching the [full game replay](https://www.youtube.com/watch?v=fEgsMYE4OAo) and the total on the final scoreboard of 8 (this happened in the second half) can only have happened if this ghost pop was credited to him.

I don't really know much more -- tried to search the issues here and didn't seem to see any possible dupes.  Maybe this is a specific instance of a more general issue, but without knowing the inner workings of the game I can't say.

Maybe portals don't activate at the same time as a pop very often, and when it does happen it's probably not common for anyone to be driving over the exit within the next few seconds.

**Comment by NewCompte** [comment]
Very interesting bug, thanks for the report. I can definitely see how this can happen in the code.

**Comment by NewCompte** [comment]
Fix is done. It can be pushed to the servers without a restart.
