### ISSUE TITLE
Spawn shadow when joining leads to socket error

### ISSUE THREAD

**Issue by SomeBall-1** [tagpro-game/tagpro-issues#86]
When joining or refreshing a game, if the game tab is in the background the client gives a socket error and when switched back to the foreground no spawn shadow is shown. I believe this comes from `tr.drawSpawn` attempting to add a sprite to `tr.layers.foreground` before it has been created.

**Comment by steppin** [comment]
should be same issue as #90, thanks!

**Comment by SomeBall-1** [comment]
@steppin Let's be real now, #90 is the same issue as this.

**Comment by steppin** [comment]
it's true :)

**Comment by steppin** [comment]
Thanks for the report.  This should be fixed.  Let us know if that's not the case!
