### ISSUE TITLE
[Enhancement] The 'disable particle effects' setting should persist across servers

### ISSUE THREAD

**Issue by RonSpawnson** [tagpro-game/tagpro-issues#87]

**Comment by RonSpawnson** [comment]
http://www.reddit.com/r/TagPro/comments/2s1llp/how_come_the_setting_for_disabling_particle/

**Comment by RonSpawnson** [comment]
There are other settings that persist, such as collecting stats. Can we please have this setting behave the same way?

**Comment by Nick-Riggs** [comment]
Yes, this is the way it should work.
