### ISSUE TITLE
[Suggestion] Don't have 3 second spawn shadows before the countdown ends?

### ISSUE THREAD

**Issue by AnneFrankTP** [tagpro-game/tagpro-issues#91]
I don't know if this is the correct place for this, but I don't think that you should have a 3 second shadow when you first join if the countdown timer is still going. It doesn't hurt the other team, like insta-join late people that spawn on the fc. It provides more time for spawn changing for people in league play as well.

**Comment by RonSpawnson** [comment]
+1

**Comment by AndrewNg** [comment]
Agreed, this has pretty big implications for competitive play.

**Comment by AMorporkian** [comment]
This has been resolved in the latest patch. Closing.
